Repository istio/release-builder, pull requests merged in 2019-10, with the labels that each got.

#5 Make dependencies a typed struct instead of list
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/github.go
  pkg/source.go
  pkg/util/files.go
  release/daily.sh
Labels: cla: yes, size/L

#6 Use the new license checker instead of the old.
  CODEOWNERS
  pkg/build/build.go
Labels: cla: yes, size/XS

#8 Add test to build and publish a release
  test/publish.sh
Labels: cla: yes, size/M

#7 Validate only the input manifest
  pkg/manifest.go
  test/publish.sh
Labels: cla: yes, size/XS

#9 Add validation tests for final release binary
  pkg/build/archive.go
  pkg/build/build.go
  pkg/build/helm.go
  pkg/source.go
  test/publish.sh
  test/validation_test.go
Labels: cla: yes, size/L

#10 Add support for GCS aliases
  pkg/publish/cmd.go
  pkg/publish/docker.go
  pkg/publish/gcs.go
  pkg/publish/github.go
Labels: cla: yes, size/M

#12 Update common files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/license-lint.yml
  common/scripts/check_clean_repo.sh
  common/scripts/gobuild.sh
  go.mod
  go.sum
Labels: cla: yes, size/L

#11 Use built in license-lint binary
  pkg/build/build.go
Labels: cla: yes, size/S

#13 Update common files.
  Makefile
  Makefile.overrides.mk
  common/.commonfiles.sha
Labels: cla: yes, size/M

#14 Support packaging the operator
  go.mod
  go.sum
  pkg/build/archive.go
  pkg/build/helm.go
  pkg/model/model.go
  pkg/util/files.go
  test/publish.sh
  test/validation_test.go
Labels: cla: yes, size/L

#15 Add standalone istioctl archive
  pkg/build/archive.go
  test/publish.sh
  test/validation_test.go
Labels: cla: yes, size/L

#16 Fix istioctl archive for windows
  pkg/build/archive.go
Labels: cla: yes, size/XS

#17 Support new hub and tags
  pkg/build/helm.go
Labels: cla: yes, size/S

#18 Fix version and tag replacement
  pkg/build/helm.go
  pkg/util/command.go
Labels: cla: yes, size/XS

#19 Finalize github publish
  pkg/publish/github.go
Labels: cla: yes, size/M

#20 Include transitive dependencies
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/github.go
  pkg/source.go
  test/validation_test.go
Labels: cla: yes, size/M

#21 Add official release and publish triggers
  release/README.md
  release/build.sh
  release/publish.sh
  release/trigger-build
  release/trigger-publish
Labels: cla: yes, size/L

#22 Add publish and build trigger warnings
  release/build-warning.sh
  release/publish-warning.sh
Labels: cla: yes, size/M

#24 Trigger build of 1.4.0-alpha.0
  release/trigger-build
Labels: cla: yes, size/XS

#25 Use service account auth instead of docker
  release/build.sh
  release/publish.sh
  release/trigger-build
Labels: cla: yes, size/S

#26 Fix braces for credentials
  release/build.sh
  release/publish.sh
  release/trigger-build
Labels: cla: yes, size/XS

#27 Trigger build one more time
  release/trigger-build
Labels: cla: yes, size/XS

#29 Add operator docker images
  pkg/build/docker.go
Labels: cla: yes, size/XS

#28 Trigger 1.4.0-alpha.0
  release/trigger-build
Labels: cla: yes, size/XS

#30 Fix release branch
  release/build.sh
  release/trigger-build
Labels: cla: yes, size/XS

#31 Trigger another build of 1.4.0-alpha.0
  release/trigger-build
Labels: cla: yes, size/XS

#32 Temporary work arounds for gcloud auth
  release/build.sh
  release/publish.sh
Labels: cla: yes, size/S

#33 Trigger 1.4.0-alpha.0
  release/trigger-build
Labels: cla: yes, size/XS

#34 Publish 1.4.0-alpha.0
  release/trigger-publish
Labels: cla: yes, size/XS

#35 Fix GITHUB variable and republish 1.4.0-alpha.0
  release/publish.sh
  release/trigger-publish
Labels: cla: yes, size/XS

#36 Support github token file
  README.md
  pkg/publish/cmd.go
  pkg/publish/github.go
  release/publish.sh
  release/trigger-publish
Labels: cla: yes, size/M

#37 Trim github token file
  pkg/publish/cmd.go
  release/trigger-publish
Labels: cla: yes, size/XS

#38 Pass full SHA to manifest for transitive dependency
  pkg/build/build.go
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/github.go
  pkg/source.go
  release/build.sh
  test/publish.sh
  test/validation_test.go
Labels: cla: yes, size/L

#39 Add test for license
  test/validation_test.go
Labels: cla: yes, size/S

#40 Build 1.4.0-beta.0
  release/trigger-build
Labels: cla: yes, size/XS

#41 Publish 1.4.0-beta.0
  release/trigger-publish
Labels: cla: yes, size/XS

#42 Add istio-demo.yaml
  pkg/build/archive.go
  test/validation_test.go
Labels: cla: yes, size/S

#44 Support custom proxy binary
  pkg/build/docker.go
  pkg/manifest.go
  pkg/model/model.go
Labels: cla: yes, size/S

#45 Support license folder
  pkg/build/build.go
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/github.go
  pkg/source.go
  release/build.sh
  test/publish.sh
  test/validation_test.go
Labels: cla: yes, size/L

#46 Move validation test to a main() instead of test
  Makefile.core.mk
  pkg/cmd/root.go
  pkg/model/model.go
  pkg/validate/cmd.go
  pkg/validate/validate.go
  release/build.sh
  test/publish.sh
  test/validation_test.go
Labels: cla: yes, size/XL

#47 pass HUB to make, for operator charts
  pkg/publish/docker.go
  pkg/util/command.go
Labels: cla: yes, size/S

#48 Trigger the 1.4-beta.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#49 fix test-infra branch and retrigger build
  release/build.sh
  release/trigger-build
Labels: cla: yes, size/XS

#50 Publish 1.4.0-beta.1
  release/trigger-publish
Labels: cla: yes, size/XS

#51 Extend readme to describe how to produce a build
  README.md
Labels: cla: yes, size/M
