Repository istio/release-builder, pull requests merged in 2019-12, with the labels that each got.

#88 Build Istio 1.4.1
  release/trigger-build
Labels: cla: yes, size/XS

#89 Publish 1.4.1
  release/trigger-publish
Labels: cla: yes, size/XS

#92 Remove archiving istio-iptables.sh
  pkg/build/archive.go
Labels: cla: yes, size/XS

#94 Publish 1.4.2
  release/trigger-publish
Labels: cla: yes, size/XS

#95 Fix Release Notes links in GitHub releases
  pkg/publish/github.go
Labels: cla: yes, ok-to-test, size/XS

#96 [release-1.4] Fix Release Notes links in GitHub releases
  pkg/publish/github.go
Labels: cla: yes, size/XS

#98 Support setting env for scripts (#97)
  pkg/build/archive.go
  pkg/util/command.go
Labels: cla: yes, size/S

#100 Tag repo with Go compatible version names
  go.mod
  go.sum
  licenses/github.com/Masterminds/semver/v3/LICENSE.txt
  pkg/model/model.go
  pkg/publish/github.go
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/M

#91 Hide proxy override from output
  pkg/model/model.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#103 Update common files
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/license-lint.yml
Labels: cla: yes, size/M

#102 [release-1.4] Hide proxy override from output
  pkg/model/model.go
Labels: cla: yes, size/XS

#104 Adding Installer as a configurable dependency in release-builder.
  pkg/model/model.go
Labels: cla: yes, size/XS

#105 Expect debian binaries in the TARGET_OUT directory
  pkg/build/debian.go
Labels: cla: yes, size/XS

#106 Package istioctl in new makefile model
  pkg/build/archive.go
Labels: cla: yes, size/XS

#107 Copy istioctl.completion from correct location
  pkg/build/archive.go
Labels: cla: yes, size/XS

#108 Triggering alpha 1.5 build
  release/build.sh
  release/trigger-build
Labels: cla: yes, size/S

#109 trigger publish for 1.5.0-alpha.0
  release/trigger-publish
Labels: cla: yes, size/XS

#111 Add validation for proxy version
  pkg/validate/validate.go
Labels: cla: yes, size/M
