Repository istio/release-builder, pull requests merged in 2019-11, with the labels that each got.

#52 Support alternative docker folders
  README.md
  pkg/build/docker.go
  pkg/model/model.go
  pkg/util/command.go
  pkg/util/files.go
  pkg/validate/validate.go
Labels: cla: yes, size/M

#54 Add operator deploy/ and samples/
  pkg/build/archive.go
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: cla: yes, size/M

#53 Trigger build of 1.4.0-beta.2
  release/trigger-build
Labels: cla: yes, size/XS

#56 trigger 1.4.0-beta.2 build
  release/trigger-build
Labels: cla: yes, size/XS

#55 Publish 1.4.0-beta.2
  release/trigger-publish
Labels: cla: yes, size/XS

#58 Update for release-1.4 branch
  CODEOWNERS
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/scripts/lint_go.sh
  test/publish.sh
Labels: cla: yes, size/M

#59 Trigger build of 1.4.0-beta.3
  release/trigger-build
Labels: cla: yes, size/XS

#61 Publish 1.4.0-beta.3
  release/trigger-publish
Labels: cla: yes, size/XS

#63 Build 1.4.0-beta.4
  release/trigger-build
Labels: cla: yes, size/XS

#62 Publish 1.4.0-beta.4
  release/trigger-publish
Labels: cla: yes, size/XS

#65 Trigger beta.5 build
  release/trigger-build
Labels: cla: yes, size/XS

#66 Publish beta.5
  release/trigger-publish
Labels: cla: yes, size/XS

#67 Compress licenses
  pkg/build/build.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#68 Fix license tar structure
  pkg/build/build.go
Labels: cla: yes, size/XS

#69 [release-1.4] Compress licenses
  pkg/build/build.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#70 [release-1.4] Fix license tar structure
  pkg/build/build.go
Labels: cla: yes, size/XS

#71 Build Istio 1.4.0
  release/trigger-build
Labels: cla: yes, size/XS

#72 Publish 1.4.0
  release/trigger-publish
Labels: cla: yes, size/XS

#74 Add istioctl completion files to archive
  pkg/build/archive.go
  pkg/validate/validate.go
Labels: cherrypick/release-1.4, cla: yes, size/S

#75 [release-1.4] Add istioctl completion files to archive
  pkg/build/archive.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#76 Fix error message file path
  pkg/validate/validate.go
Labels: cherrypick/release-1.4, cla: yes, size/XS

#73 Override proxy by url rather than local file
  Makefile.core.mk
  README.md
  pkg/build/docker.go
  pkg/model/model.go
  release/build.sh
Labels: cherrypick/release-1.4, cla: yes, size/S

#78 [release-1.4] Fix error message file path
  pkg/validate/validate.go
Labels: cla: yes, size/XS

#77 Print the correct env variable
  pkg/util/command.go
Labels: cla: yes, size/XS

#79 [release-1.4] Override proxy by url rather than local file
  Makefile.core.mk
  README.md
  pkg/build/docker.go
  pkg/model/model.go
  release/build.sh
Labels: cla: yes, size/S

#80 Update version in requirements.yaml
  pkg/build/helm.go
Labels: cla: yes, ok-to-test, size/XS

#81 [release-1.4] Update version in requirements.yaml
  pkg/build/helm.go
Labels: cla: yes, size/XS

#82 Tag installer repo
  release/build.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#83 [release-1.4] Tag installer repo
  release/build.sh
Labels: cla: yes, size/XS

#84 Don't show full system env
  pkg/util/command.go
Labels: cla: yes, size/XS

#85 variablize manifest dependencies
  release/build.sh
Labels: cherrypick/release-1.4, cla: yes, size/XS

#86 [release-1.4] variablize manifest dependencies
  release/build.sh
Labels: cla: yes, size/XS
