Repository istio/release-builder, pull requests merged in 2020-02, with the labels that each got.

#129 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#130 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#132 Trigger 1.5-beta.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#133 Publish 1.5.0-beta.1
  release/trigger-publish
Labels: cla: yes, size/XS

#134 Publish 1.4.4
  release/trigger-publish
Labels: cla: yes, size/XS

#135 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#136 Trigger 1.4.5 build
  release/trigger-build
Labels: cla: yes, size/XS

#137 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#138 trigger beta 2
  release/trigger-build
Labels: cla: yes, size/XS

#139 Remove legacy helm installation
  pkg/build/archive.go
  pkg/validate/validate.go
  test/publish.sh
Labels: cla: yes, size/M

#141 publishing beta 2
  release/trigger-publish
Labels: cla: yes, size/XS

#142 Fix more references to Helm
  pkg/build/archive.go
  pkg/build/build.go
  pkg/build/helm.go
Labels: cla: yes, size/L

#143 Publish Istio 1.4.5
  release/trigger-publish
Labels: cla: yes, size/XS

#144 Set the right branches for the build process
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/S

#146 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#145 Build 1.5.0 beta.3
  release/trigger-build
Labels: cla: yes, size/XS

#147 Retrigger beta3
  release/trigger-build
Labels: cla: yes, size/XS

#148 Trigger beta-3 build for release 1.5
  release/trigger-build
Labels: cla: yes, size/XS

#149 Trigger publish of beta3 for release-1.5
  release/trigger-publish
Labels: cla: yes, size/XS

#150 Document how to build locally
  README.md
  example/manifest.yaml
Labels: cla: yes, size/M

#151 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#152 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#154 Minor improvements to the release builder
  pkg/util/files.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#155 Release 1 5 beta4
  release/trigger-build
Labels: cla: yes, size/XS

#156 Publish release-1.5-beta4
  release/trigger-publish
Labels: cla: yes, size/XS
