Repository istio/release-builder, pull requests merged in 2020-12, with the labels that each got.

#498 [release-1.7] [1.8] Cherrypick #448, GCR mirror
  release/publish.sh
Labels: cla: yes, release-notes-none, size/XS

#499 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#501 trigger 1.8.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#500 Trigger 1.7.6 build
  release/trigger-build
Labels: cla: yes, size/XS

#502 publish 1.8.1
  release/trigger-publish
Labels: cla: yes, size/XS

#503 Publish 1.7.6
  release/trigger-publish
Labels: cla: yes, size/XS

#504 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#506 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#505 Fix some directory issues in the container based build
  README.md
  example/manifest.yaml
  pkg/util/command.go
Labels: cla: yes, size/M
