Repository istio/release-builder, pull requests merged in 2020-05, with the labels that each got.

#222 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#223 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#224 Include samples/certs/Makefile in distribution
  pkg/build/archive.go
Labels: cherrypick/release-1.6, cla: yes, size/XS

#226 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#225 [release-1.6] Include samples/certs/Makefile in distribution
  pkg/build/archive.go
Labels: cla: yes, size/XS

#227 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#228 Automator: update common-files@release-1.6 in istio/release-builder@release-1.6
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#229 Trigger 1.5.3 build
  release/trigger-build
Labels: cla: yes, size/XS

#194 [release-1.4] Fix the logic to identify SHA from a git tag
  pkg/source.go
Labels: cla: yes, size/XS

#232 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#230 Trigger 1.6 beta 1
  release/trigger-build
Labels: cla: yes, size/XS

#231 Trigger publish of 1.6 beta 1
  release/trigger-publish
Labels: cla: yes, size/XS

#234 Automator: update common-files@release-1.6 in istio/release-builder@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#237 Trigger publish of 1.4.9
  release/trigger-publish
Labels: cla: yes, size/XS

#238 Trigger publish of 1.5.3
  release/trigger-publish
Labels: cla: yes, size/XS

#239 trigger 1.5.4 build
  release/trigger-build
Labels: cla: yes, size/XS

#240 Publish 1.5.4
  release/trigger-publish
Labels: cla: yes, size/XS

#241 Automator: update common-files@release-1.5 in istio/release-builder@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#242 Generate compiled in charts for operator binary
  pkg/build/docker.go
Labels: cherrypick/release-1.6, cla: yes, size/XS

#243 [release-1.6] Generate compiled in charts for operator binary
  pkg/build/docker.go
Labels: cla: yes, size/XS

#235 Build 1.6.0-rc.0
  release/trigger-build
Labels: cla: yes, size/XS

#236 Publish 1.6.0-rc.0
  release/trigger-publish
Labels: cla: yes, size/XS

#244 Trigger 1.6 rc1
  release/trigger-build
Labels: cla: yes, size/XS

#245 Public 1.6 rc1
  release/trigger-publish
Labels: cla: yes, size/XS

#247 Trigger 1.6 rc2
  release/trigger-build
Labels: cla: yes, size/XS

#248 Trigger publish of 1.6
  release/trigger-publish
Labels: cla: yes

#249 Print out manifest in publish warning
  release/publish-warning.sh
Labels: cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/XS

#250 [release-1.6] Print out manifest in publish warning
  release/publish-warning.sh
Labels: cla: yes, size/XS

#251 [release-1.5] Print out manifest in publish warning
  release/publish-warning.sh
Labels: cla: yes, size/XS

#252 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#254 Build 1.6.0 final
  release/trigger-build
Labels: cla: yes, size/XS

#255 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#256 Trigger 1.6 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#257 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#258 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
