Repository istio/release-builder, pull requests merged in 2020-07, with the labels that each got.

#298 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#299 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#300 Trigger a 1.7.0-alpha.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#301 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#302 Build 1.6.5
  release/trigger-build
Labels: cla: yes, size/XS

#303 Trigger 1.5.8 build
  release/trigger-build
Labels: cla: yes, size/XS

#304 Publish 1.7.0-alpha.0
  release/trigger-publish
Labels: cla: yes, size/XS

#305 Re-trigger another build of 1.5.8
  release/trigger-build
Labels: cla: yes, size/XS

#306 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#308 Publish 1.6.5
  release/trigger-publish
Labels: cla: yes

#309 Publish 1.5.8
  release/trigger-publish
Labels: cla: yes, size/XS

#310 Automator: update common-files@release-1.6 in istio/release-builder@release-1.6
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/S

#311 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#312 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#314 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#315 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#316 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#317 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/S

#318 Use MARKDOWN_LINT_ALLOWLIST instead of _WHITELIST
  Makefile.core.mk
Labels: cla: yes, size/XS

#319 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#321 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#322 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#323 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#324 Set release managers as CODEOWNERS for release-1.7
  CODEOWNERS
Labels: cla: yes, size/XS

#325 Updates for 1.7
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/M

#307 Move grafana dashboards path
  pkg/build/grafana.go
Labels: cla: yes, size/XS

#326 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#328 Trigger a 1.7.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#329 Publish 1.7.0-alpha.1
  release/trigger-publish
Labels: cla: yes, size/XS

#330 Publish 1.7.0-alpha.1
  release/trigger-publish
Labels: cla: yes, size/XS

#327 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#332 Remove mixer dashboards
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/XS

#331 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#333 Trigger 1.6.6 build.
  release/trigger-build
Labels: cla: yes, size/XS

#320 Remove operator deploy verification
  pkg/build/archive.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#336 trigger 1.6.6 build
  release/trigger-build
Labels: cla: yes, size/XS

#335 Add envoy into deps and proxy_workspace auto resolving
  README.md
  example/manifest.yaml
  pkg/model/model.go
  pkg/source.go
  pkg/util/files.go
  release/build.sh
  test/publish.sh
Labels: cherrypick/release-1.7, cla: yes, size/M

#337 [release-1.7] Add envoy into deps and proxy_workspace auto resolving (#335)
  README.md
  example/manifest.yaml
  pkg/model/model.go
  pkg/source.go
  pkg/util/files.go
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/M

#339 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#340 remove convert_RbacConfig_to_ClusterRbacConfig.sh from the archive
  pkg/build/archive.go
Labels: cla: yes, size/XS

#341 Trigger alpha2 build
  release/trigger-build
Labels: cla: yes, size/XS

#342 Trigger alpha2 publishing
  release/trigger-publish
Labels: cla: yes, size/XS

#343 skip adding enovy dep if it is nil
  pkg/source.go
Labels: cherrypick/release-1.7, cla: yes, size/XS

#344 [release-1.7] skip adding enovy dep if it is nil
  pkg/source.go
Labels: cla: yes, release-notes-none, size/XS

#345 Publish 1.6.6
  release/trigger-publish
Labels: cla: yes, size/XS

#346 Trigger build
  release/trigger-build
Labels: cla: yes

#347 Trigger 1.6.7 release
  release/trigger-publish
Labels: cla: yes
