Repository istio/release-builder, pull requests merged in 2020-01, with the labels that each got.

#112 Build 1.4.3
  release/trigger-build
Labels: cla: yes, size/XS

#113 Fix client go not being tagged with go version
  pkg/source.go
Labels: cla: yes, size/XS

#114 Publish 1.4.3
  release/trigger-publish
Labels: cla: yes, size/XS

#115 Remove operator repo
  README.md
  pkg/build/archive.go
  pkg/build/docker.go
  pkg/model/model.go
  pkg/validate/validate.go
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/M

#117 Release 1.5 common files update
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#118 Automator: update common-files@master in istio/release-builder@master
  LICENSE
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#121 Revert "Update for release-1.5 branch"
  CODEOWNERS
  test/publish.sh
Labels: cla: yes, size/S

#122 Update for the actual release-1.5 branch
  CODEOWNERS
  LICENSE
  common/.commonfiles.sha
  test/publish.sh
Labels: cla: yes, size/S

#119 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: cla: yes, size/M

#123 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#124 Update common files to 1.5 branch
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#125 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS

#126 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/lint_go.sh
Labels: cla: yes, size/XS

#127 Trigger 1.5 beta0 build
  release/trigger-build
Labels: cla: yes, size/XS

#128 Publish beta.0
  release/trigger-publish
Labels: cla: yes, size/XS
