Repository istio/release-builder, pull requests merged in 2020-03, with the labels that each got.

#157 Update trigger-build
  release/trigger-build
Labels: cla: yes, size/XS

#158 Publish 1.5.0-beta.5
  release/trigger-publish
Labels: cla: yes, size/XS

#153 Add grafana to build step
  README.md
  pkg/build/build.go
  pkg/build/grafana.go
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/cmd.go
  pkg/publish/grafana.go
  pkg/validate/validate.go
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/L

#159 Trigger publish of 1.4.6
  release/trigger-publish
Labels: cla: yes, size/XS

#160 trigger 1.5.0
  release/trigger-build
Labels: cla: yes, size/XS

#161 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#162 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#163 Publish 1.5.0
  release/trigger-publish
Labels: cla: yes, size/XS

#164 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#165 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#166 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#167 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#168 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/L

#169 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, size/XS

#170 Fix grafana inputs field name
  pkg/build/grafana.go
Labels: cla: yes, size/XS

#171 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#172 Trigger a 1.6.0-alpha.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#174 Add grafana token to official publish
  release/publish.sh
Labels: cla: yes, size/XS

#173 Publish 1.6.0-alpha.0
  release/trigger-publish
Labels: cla: yes, size/XS

#175 Automator: update common-files@release-1.5 in istio/release-builder@release-1.5
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#176 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#177 Trigger publish of 1.4.7
  release/trigger-publish
Labels: cla: yes, size/XS

#178 Publish 1.5.1
  release/trigger-publish
Labels: cla: yes, size/XS

#180 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#181 Fix grafana publish
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/XS

#179 addition of ARMv7 and ARM64 builds
  README.md
  pkg/build/archive.go
  pkg/validate/validate.go
Labels: cla: yes, ok-to-test, size/S
