Repository istio/release-builder, pull requests merged in 2020-10, with the labels that each got.

#427 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#428 Automator: update common-files@release-1.6 in istio/release-builder@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#429 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#430 Trigger 1.6.12 build
  release/trigger-build
Labels: cla: yes, size/XS

#431 Re build 1.6.12
  release/trigger-build
Labels: cla: yes, size/XS

#432 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#434 Publish 1.6.12
  release/trigger-publish
Labels: cla: yes

#433 Include .sh files in samples
  pkg/build/archive.go
Labels: cla: yes, size/XS

#435 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#436 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#437 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#438 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#442 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#443 [release-1.8] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: cla: yes, release-notes-none, size/S

#444 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#445 trigger 1.8 alpha release
  release/trigger-build
Labels: cla: yes, size/XS

#446 publish the 1.8 alpha
  release/trigger-publish
Labels: cla: yes, size/XS

#447 Trigger release 1.6.13 build
  release/trigger-build
Labels: cla: yes, size/XS

#440 Trigger 1.7.4 build
  release/trigger-build
Labels: cla: yes, size/XS

#453 second alpha release for community testing
  release/trigger-build
Labels: cla: yes, size/XS

#454 Update to envoy to use istio/envoy and add new dashboard
  example/manifest.yaml
  test/publish.sh
Labels: cla: yes, size/XS

#449 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#441 Publish 1.7.4
  release/trigger-publish
Labels: cla: yes, size/XS

#455 Bump 1.8 alpha tag to create a new build
  release/trigger-build
Labels: cla: yes, size/XS

#452 Publish istio 1.6.13
  release/trigger-publish
Labels: cla: yes, size/XS

#456 Add extension dashboard
  release/build.sh
Labels: cla: yes, size/XS

#457 Fix dashboard for 1.8
  example/manifest.yaml
  release/build.sh
  release/trigger-build
  test/publish.sh
Labels: cla: yes, size/XS

#459 publish 1.8.0-alpha.2
  release/trigger-publish
Labels: cla: yes, size/XS

#461 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#462 [release-1.8] Include tools/certs/common.mk
  pkg/build/archive.go
Labels: cla: yes, release-notes-none, size/XS

#463 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#464 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
