Repository istio/release-builder, pull requests merged in 2020-06, with the labels that each got.

#261 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#262 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, size/XS

#259 Trigger 1.6.1
  release/trigger-build
Labels: cla: no, cla: yes, size/XS

#263 Add /tools/certs/ to the release package.
  pkg/build/archive.go
Labels: cherrypick/release-1.6, cla: yes, size/XS

#264 [release-1.6] Add /tools/certs/ to the release package.
  pkg/build/archive.go
Labels: cla: yes, size/XS

#265 Rebuild 1.6.1
  release/trigger-build
Labels: cla: yes, size/XS

#266 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/XS

#267 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#268 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: auto-merge, cla: yes, size/XS

#269 Trigger 1.6 build
  release/trigger-build
Labels: cla: yes, size/XS

#260 Publish 1.6.1
  release/trigger-publish
Labels: cla: yes

#270 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/M

#273 Publish 1.6.2
  release/trigger-publish
Labels: cla: yes, size/XS

#275 Publish 1.5.5
  release/trigger-publish
Labels: cla: yes, size/XS

#276 Build163
  release/trigger-build
Labels: cla: yes, size/XS

#277 Trigger build for 1.5.6
  release/trigger-build
Labels: cla: yes, size/XS

#278 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/copyright-banner-go.txt
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/M

#271 Scan base image for vulerabilities during build
  example/manifest.yaml
  pkg/build/build.go
  pkg/build/scanner.go
  pkg/manifest.go
  pkg/model/model.go
Labels: cla: yes, size/L

#279 Trigger163build
  release/trigger-build
Labels: cla: yes, size/XS

#280 Build Istio 1.4.10
  release/trigger-build
Labels: cla: yes, size/XS

#281 CNI is no longer a dependency, it's part of istio/istio
  README.md
  example/manifest.yaml
  pkg/build/docker.go
  pkg/model/model.go
  pkg/validate/validate.go
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/M

#282 Publish 1.5.6
  release/trigger-publish
Labels: cla: yes, size/XS

#284 Publish 1.6.3
  release/trigger-publish
Labels: cla: yes, size/XS

#283 Publish 1.4.10
  release/trigger-publish
Labels: cla: yes, size/XS

#285 [release-1.6] Scan base image for vulerabilities during build
  example/manifest.yaml
  pkg/build/build.go
  pkg/build/scanner.go
  pkg/manifest.go
  pkg/model/model.go
  test/publish.sh
Labels: cla: yes, size/L

#286 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#288 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#287 [release-1.5] Manual cherrypick of #271 (Scan base image)
  example/manifest.yaml
  pkg/build/build.go
  pkg/build/scanner.go
  pkg/manifest.go
  pkg/model/model.go
Labels: cla: yes, size/L

#289 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#290 Ignore vulnerability scans during testing
  test/publish.sh
Labels: cherrypick/release-1.5, cherrypick/release-1.6, cla: yes, size/XS

#292 [release-1.6] Ignore vulnerability scans during testing
  test/publish.sh
Labels: cla: yes, size/XS

#291 [release-1.5] Ignore vulnerability scans during testing
  test/publish.sh
Labels: cla: yes, size/XS

#293 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/fix_copyright_banner.sh
Labels: auto-merge, cla: yes, size/XS

#294 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, size/XS

#295 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#296 Trigger 1.6.4
  release/trigger-publish
Labels: cla: yes, size/XS

#297 Trigger publish of 1.5.7
  release/trigger-publish
Labels: cla: yes, size/XS
