Repository istio/release-builder, pull requests merged in 2020-08, with the labels that each got.

#353 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#349 Do not report a dirty/modified tree
  pkg/util/command.go
Labels: cherrypick/release-1.7, cla: yes, size/XS

#350 Use MkdirAll instead of Mkdir to help local testing
  pkg/build/build.go
  pkg/source.go
Labels: cherrypick/release-1.7, cla: yes, size/XS

#351 Bump test version
  test/publish.sh
Labels: cla: yes, size/XS

#355 [release-1.7] Use MkdirAll instead of Mkdir to help local testing
  pkg/build/build.go
  pkg/source.go
Labels: cla: yes, release-notes-none, size/XS

#354 [release-1.7] Do not report a dirty/modified tree
  pkg/util/command.go
Labels: cla: yes, release-notes-none, size/XS

#356 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#352 [release-1.7] Bump test version
  test/publish.sh
Labels: cla: yes, size/XS

#358 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#359 Trigger beta1 build
  release/trigger-build
Labels: cla: yes, size/XS

#360 Publish beta1
  release/trigger-publish
Labels: cla: yes, size/XS

#361 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#362 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#363 Fix example manifest
  example/manifest.yaml
Labels: cla: yes, size/XS

#364 Add manifests/examples to the release
  pkg/build/archive.go
Labels: cherrypick/release-1.7, cla: yes, size/S

#365 [release-1.7] Add manifests/examples to the release
  pkg/build/archive.go
Labels: cla: yes, release-notes-none, size/S

#367 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#368 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#366 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#369 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci-format.yml
  common/scripts/format_go.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#370 Trigger beta2 build
  release/trigger-build
Labels: cla: yes, size/XS

#371 Publish beta2
  release/trigger-publish
Labels: cla: yes, size/XS

#372 Trigger 1.6.8 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#373 Update for the actual release-1.5 branch (#122)
  release/trigger-publish
Labels: cla: yes, size/XS

#338 [release-1.6] Add envoy into deps and proxy_workspace auto resolving (#335)
  README.md
  example/manifest.yaml
  pkg/model/model.go
  pkg/source.go
  pkg/util/files.go
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/M

#374 Trigger RC.1
  release/trigger-build
Labels: cla: yes, size/XS

#376 Trigger RC.1
  release/trigger-build
Labels: cla: yes, size/XS

#375 Publish RC1
  release/trigger-publish
Labels: cla: yes, size/XS

#357 Fix client-go versioning
  pkg/model/model.go
Labels: cla: yes, size/XS

#378 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#380 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#379 Remove ISTIO_VERSION variable
  pkg/util/command.go
Labels: cla: yes, size/XS

#377 Trigger RC2 build
  release/trigger-build
Labels: cla: yes, size/XS

#381 Publish RC2
  release/trigger-publish
Labels: cla: yes, size/XS

#384 Trigger 1.5.10 build
  release/trigger-build
Labels: cla: yes, size/XS

#385 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#382 Trigger RC3 build
  release/trigger-build
Labels: cla: yes, size/XS

#386 Publish RC3
  release/trigger-publish
Labels: cla: yes, size/XS

#389 Trigger RC4 build
  release/trigger-build
Labels: cla: yes, size/XS

#393 Trigger publish 1.5.10
  release/trigger-publish
Labels: cla: yes, size/XS

#394 Use addon as a grafana dashboards path
  pkg/build/grafana.go
Labels: cla: yes, size/S

#396 Build 1.6.9
  release/trigger-build
Labels: cla: yes, size/XS

#399 Build169
  release/trigger-build
Labels: cla: yes, size/XS

#398 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#392 Fix spelling errors in readme.md
  release/README.md
Labels: cla: yes, size/XS
