Repository istio/release-builder, pull requests merged in 2020-04, with the labels that each got.

#182 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, size/XS

#183 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#184 Trigger a 1.6.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#186 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#187 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#188 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#189 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  pkg/build/archive.go
Labels: auto-merge, cla: yes, size/S

#190 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#191 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#193 Fix the logic to identify SHA from a git tag
  pkg/source.go
Labels: cherrypick/release-1.4, cherrypick/release-1.5, cla: yes, size/XS

#197 Update manifest chart and script paths
  pkg/build/archive.go
  pkg/build/grafana.go
  pkg/validate/validate.go
Labels: cla: yes, do-not-merge, size/S

#198 Add gen-charts target to make istioctl
  pkg/build/archive.go
Labels: cla: yes, size/XS

#199 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#196 Trigger build for 1.4.8
  release/trigger-build
Labels: cla: yes, size/XS

#200 Build 1.4.8
  release/trigger-build
Labels: cla: yes, size/XS

#201 Trigger another 1.4.8 build
  release/trigger-build
Labels: cla: yes, size/XS

#202 [release-1.4] Trigger another 1.4.8 build
  release/trigger-build
Labels: cla: yes, size/XS

#203 trigger 1.5.2 build
  release/trigger-build
Labels: cla: yes, size/XS

#204 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#205 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, size/S

#206 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#208 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/check_no_modify.sh
  common/scripts/nomodify.md5
Labels: auto-merge, cla: yes, size/S

#209 Trigger 1.6 alpha 2 build
  release/trigger-build
Labels: cla: yes, size/XS

#210 Trigger 1.6.0-alpha.2 to be published
  release/trigger-publish
Labels: cla: yes, size/XS

#211 Trigger publish of 1.4.8
  release/trigger-publish
Labels: cla: yes, size/XS

#212 Trigger publish on 1.5.2
  release/trigger-publish
Labels: cla: yes, size/XS

#213 Update common files
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#214 Update codeowners
  CODEOWNERS
Labels: cla: yes, size/XS

#215 Set branches
  release/build.sh
Labels: cla: yes, size/S

#216 Trigger 1.6 beta 0
  release/trigger-build
Labels: cla: yes, size/XS

#217 Update build.sh
  CODEOWNERS
  release/build.sh
Labels: cla: yes, size/XS

#218 Retrigger 16 beta 0
  release/trigger-build
Labels: cla: yes, size/XS

#219 Publish 1.6 beta0
  release/trigger-publish
Labels: cla: yes, size/XS

#220 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/S

#221 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS
