Repository istio/release-builder, pull requests merged in 2020-11, with the labels that each got.

#465 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#466 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#467 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#468 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#469 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#470 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#471 Create 1.8-alpha.3 build
  release/trigger-build
Labels: cla: yes, size/XS

#472 Update build file and trigger alpha.3 build again
  release/trigger-build
Labels: cla: yes, size/XS

#474 Update to point to envoyproxy/envoy
  example/manifest.yaml
  test/publish.sh
Labels: cla: yes, size/XS

#473 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#475 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#477 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#476 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#478 Automator: update common-files@release-1.6 in istio/release-builder@release-1.6
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, size/XS

#479 Trigger 1.7.5 build
  release/trigger-build
Labels: cla: yes, size/XS

#481 Trigger 1.7.5 build
  release/trigger-build
Labels: cla: yes, size/XS

#482 Update trigger-build
  release/trigger-build
Labels: cla: yes, size/XS

#483 Update trigger-publish for rc0
  release/trigger-publish
Labels: cla: yes, size/XS

#484 [1.8] Cherrypick #448, GCR mirror
  release/publish.sh
Labels: cla: yes, size/XS

#485 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#486 Trigger rc.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#487 Trigger rc.1 build again
  release/trigger-build
Labels: cla: yes, size/XS

#488 Update trigger-publish to 1.8.0-rc.1
  release/trigger-publish
Labels: cla: yes, size/XS

#489 Trigger 1.8.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#490 Publish 1.8.0
  release/trigger-publish
Labels: cla: yes, size/XS

#480 Publish 1.7.5
  release/trigger-publish
Labels: cla: yes, size/XS

#491 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#492 Build 1.6.14
  common/scripts/gobuild.sh
  common/scripts/setup_env.sh
  release/trigger-build
Labels: cla: yes, size/XS

#494 Rebuild 1.6.14
  release/trigger-build
Labels: cla: yes

#495 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#496 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#497 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS
