Repository istio/release-builder, pull requests merged in 2020-09, with the labels that each got.

#395 Fix local build on linux
  README.md
Labels: cla: yes, size/XS

#400 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#401 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#402 Update common files (#213)
  release/trigger-build
Labels: cla: yes, size/XS

#403 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#404 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#405 trigger 1.7.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#407 trigger 1.7.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#408 Trigger 1.6.9 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#409 Copy all tools/certs/Makefile*
  pkg/build/archive.go
Labels: cla: yes, size/S

#406 trigger 1.7.1 publish
  release/trigger-publish
Labels: cla: yes

#410 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#411 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#412 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/M

#413 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#414 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#416 trigger release 1.6.10 build
  release/trigger-build
Labels: cla: yes, size/XS

#417 Trigger 1.7.2 release build
  release/trigger-build
Labels: cla: yes, size/XS

#418 Trigger 1.7.2 release publish
  release/trigger-publish
Labels: cla: yes

#419 Publish 1.6.10
  release/trigger-publish
Labels: cla: yes, size/XS

#420 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#421 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#423 Trigger 1.6.11 Publish
  release/trigger-publish
Labels: cla: yes, size/XS

#424 Trigger 1.7.3 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#425 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#426 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.yamllint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
