Repository istio/release-builder, pull requests merged in 2021-05, with the labels that each got.

#640 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#641 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#639 Trigger 1.10.0-rc.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#642 Trigger 1.10.0-rc.1 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#643 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#645 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#646 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#648 Publish 1.9.5
  release/trigger-publish
Labels: cla: yes, size/XS

#653 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#647 Trigger 1.10.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#654 Trigger second release 1.10.0 build to capture dep update
  release/trigger-build
Labels: cla: yes

#655 Trigger another 1.10.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#656 Trigger release 1.10.0 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#657 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#658 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#659 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#660 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#661 Remove validation of deleted istiod-remote charts
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: cla: yes, size/XS

#662 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#663 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#664 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#666 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#667 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#665 Trigger 1.10.1 build
  release/trigger-build
Labels: cla: yes, size/XS
