Repository istio/release-builder, pull requests merged in 2021-09, with the labels that each got.

#771 Publish 1.11.2
  release/trigger-publish
Labels: cla: yes, size/XS

#770 Switch github token used during build for image update PR
  release/build.sh
Labels: cla: yes, size/XS

#772 [release-1.11] Switch github token used during build for image update PR
  release/build.sh
Labels: cla: yes, size/XS, release-notes-none

#774 [release-1.9] Switch github token used during build for image update PR
  release/build.sh
Labels: cla: yes, size/XS, release-notes-none

#775 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#776 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#757 Add build+publish of a helm repo
  pkg/build/build.go
  pkg/build/helm.go
  pkg/publish/cmd.go
  pkg/publish/helm.go
  pkg/validate/validate.go
  release/build.sh
  release/publish.sh
  test/publish.sh
Labels: cla: yes, size/L

#778 Create 1.12.0-alpha.0
  release/trigger-build
Labels: cla: yes, size/XS

#779 Create 1.12.0-alpha.0
  release/trigger-build
Labels: cla: yes, size/XS

#780 Publish 1.12.0-alpha.0
  release/trigger-publish
Labels: cla: yes, size/XS

#773 [release-1.10] Switch github token used during build for image update PR
  release/build.sh
Labels: cla: yes, size/XS, release-notes-none

#782 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#781 Create 1.12.0-alpha.1
  release/trigger-build
Labels: cla: yes, size/XS

#783 Publish 1.12.0-alpha.1
  release/trigger-publish
Labels: cla: yes, size/XS

#784 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#785 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#786 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#787 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#788 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#789 Build 1.11.3
  release/trigger-build
Labels: cla: yes, size/XS

#791 Build 1.11.3
  release/trigger-build
Labels: cla: yes, size/XS

#792 Publish 1.11.3
  release/trigger-publish
Labels: cla: yes, size/XS

#793 Skip helm charts for CI builds
  pkg/build/build.go
Labels: cla: yes, size/S

#795 Trigger second 1.10.5 build
  release/trigger-build
Labels: cla: yes

#790 Add cosign image signing support to release-builder
  pkg/publish/cmd.go
  pkg/publish/docker.go
  release/build.sh
  release/publish.sh
  test/publish.sh
Labels: size/M, cla: yes

#797 Triggering build 1.12.0-alpha.2
  release/trigger-build
Labels: cla: yes, size/XS

#796 Updates for new tagging scheme
  pkg/publish/docker.go
  pkg/validate/validate.go
Labels: size/M, cla: yes
