Repository istio/release-builder, pull requests merged in 2021-02, with the labels that each got.

#553 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#554 build 1.9.0-rc.0
  release/trigger-build
Labels: cla: yes, size/XS

#555 publish 1.9.0-rc.0
  release/trigger-publish
Labels: cla: yes, size/XS

#558 fix dry run job by setting appropriate repo to istio/envoy not envoyproxy/envoy
  test/publish.sh
Labels: cla: yes, size/XS

#557 do not ignore CVE vulns in base images
  release/build.sh
Labels: cla: yes, size/XS

#559 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#562 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#560 build 1.9.0
  release/trigger-build
Labels: cla: yes, size/XS

#563 Trigger 1.8.3 release build
  release/trigger-build
Labels: cla: yes, size/XS

#564 Publish 1.8.3
  release/trigger-publish
Labels: cla: yes, size/XS

#561 publish 1-9-0
  release/trigger-publish
Labels: cla: yes, size/XS

#565 Update make gen to call format. Run gofumpt
  Makefile.core.mk
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/helm.go
  pkg/cmd/root.go
  pkg/model/model.go
  pkg/publish/cmd.go
  pkg/publish/gcs.go
  pkg/publish/github.go
  pkg/source.go
  pkg/util/command.go
  pkg/util/files.go
Labels: cla: yes, size/M

#556 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/S

#566 Remove dump kubernetes from release
  pkg/build/archive.go
Labels: cla: yes, size/XS

#568 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#567 Add osx-arm64 target to release
  pkg/build/archive.go
Labels: cla: yes, size/XS

#569 build 1.7.8
  release/trigger-build
Labels: cla: yes, release-notes-none, size/XS

#571 Build 1.7.8
  release/trigger-build
Labels: cla: yes, release-notes-none, size/XS

#570 Publish 1.7.8
  release/trigger-publish
Labels: cla: yes, release-notes-none

#572 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#573 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#575 Trigger 1.9.1
  release/trigger-build
Labels: cla: yes, size/XS

#576 Trigger191
  release/trigger-build
Labels: cla: yes, size/XS
