Repository istio/release-builder, pull requests merged in 2021-01, with the labels that each got.

#508 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#509 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#510 trigger build for 1.9.0-alpha.0
  release/trigger-build
Labels: cla: yes, release-notes-none, size/XS

#511 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#507 Fix hub and tag for helm charts
  pkg/build/archive.go
Labels: cla: yes, size/S

#512 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#513 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#515 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#516 trigger 1.8.2 build
  release/trigger-build
Labels: cla: yes, size/XS

#517 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#518 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#521 update common file to 1.9
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#519 Set release managers as CODEOWNERS for release-1.9
  CODEOWNERS
Labels: cla: yes, size/XS

#523 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#522 [release-1.9] stop publishing latest tags
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/S

#524 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#525 run UPDATE_BRANCH=release-1.9 make update-common
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS

#520 Use release-1.9 branch instead of master
  common/Makefile.common.mk
Labels: cla: yes, size/XS

#526 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#527 Publish 1.8.2
  release/trigger-publish
Labels: cla: yes

#529 Build 1.9.0-rc.0
  release/trigger-build
Labels: cla: yes

#531 build 1.9.0-beta.0
  release/build.sh
  release/trigger-build
Labels: cla: yes, size/XS

#530 Publish 1.9.0-beta.0
  release/trigger-publish
Labels: cla: yes, size/XS

#532 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#533 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#534 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#536 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#535 fix helm manifest hub tag; fix bad merge
  pkg/build/archive.go
  pkg/build/build.go
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: cla: yes, size/L

#538 Automator: update common-files@master in istio/release-builder@master
  .gitattributes
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#539 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#540 Add validation for helm operator manifest
  pkg/validate/validate.go
Labels: cla: yes, size/M

#537 [release-1.9] fix helm manifest hub tag; fix bad merge
  pkg/build/archive.go
  pkg/build/build.go
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: cla: yes, release-notes-none, size/L

#541 [release-1.9] Add validation for helm operator manifest
  pkg/validate/validate.go
Labels: cla: yes, release-notes-none, size/M

#542 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/L

#543 build 1.9.0-beta.1
  release/trigger-build
Labels: cla: yes, size/XS

#544 publish 1.9.0-beta.1
  release/trigger-publish
Labels: cla: yes, size/XS

#545 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb.yaml
Labels: auto-merge, cla: yes, release-notes-none, size/L

#546 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#547 Trigger 1.7.7 build
  release/trigger-build
Labels: cla: yes, size/XS

#548 Trigger 1.7.7 build
  release/trigger-build
Labels: cla: yes, size/XS

#549 Automator: update common-files@release-1.7 in istio/release-builder@release-1.7
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#550 Trigger 1.7.7 build
  release/trigger-build
Labels: cla: yes, size/XS

#551 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#552 Publish 1.7.7
  release/trigger-publish
Labels: cla: yes, size/XS

#514 Release branch automation
  Makefile.core.mk
  README.md
  example/manifest_branch.yaml
  pkg/branch/branch.go
  pkg/branch/cmd.go
  pkg/branch/createBranches.go
  pkg/branch/createToolImages.go
  pkg/branch/istioReleaseBuilderUpdates.go
  pkg/branch/setupProw.go
  pkg/branch/stopPublishingLatest.go
  pkg/branch/updateCodeOwners.go
  pkg/branch/updateCommonFiles.go
  pkg/branch/updateCommonFilesCommon.go
  pkg/branch/updateDependencies.go
  pkg/cmd/root.go
  pkg/model/model.go
  pkg/util/git.go
  release/README.md
  release/branch.sh
  release/trigger-branch
Labels: cla: yes, size/XXL
