Repository istio/release-builder, pull requests merged in 2021-04, with the labels that each got.

#597 Fix bug causing incorrect version parsing from envvar
  release/branch.sh
  release/build.sh
Labels: cla: yes, size/S

#598 Update parameter order in git command
  pkg/util/git.go
Labels: cherrypick/release-1.8, cherrypick/release-1.9, cla: yes, size/S

#599 Update trigger branch to 1.10. Helps validate an issue with version.
  release/trigger-branch
Labels: cla: yes, size/XS

#601 [release-1.9] Update parameter order in git command
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/S

#600 [release-1.8] Update parameter order in git command
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/S

#602 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#603 [release-1.10] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: cla: yes, release-notes-none, size/S

#604 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#605 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#606 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#609 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#608 Automator: update common-files@release-1.8 in istio/release-builder@release-1.8
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#607 Trigger 1.10.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#610 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#611 Point 1.10 release-builder to envoyproxy/envoy
  release/build.sh
Labels: cla: yes, size/XS

#612 Trigger 1.10.0-alpha-0 build
  release/trigger-build
Labels: cla: yes, size/XS

#613 Trigger third 1.10-alpha.0 release build
  release/trigger-build
Labels: cla: yes, size/XS

#614 Trigger another 1.10.0-alpha.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#616 Trigger 5th 1.10-alpha.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#615 Use the GITHUB_TOKEN_FILE specified in the build container
  release/branch.sh
  release/build.sh
Labels: cherrypick/release-1.10, cla: yes, size/XS

#618 Trigger publish for 1.10.0-alpha.0
  release/trigger-publish
Labels: cla: yes, size/XS

#617 [release-1.10] Use the GITHUB_TOKEN_FILE specified in the build container
  release/branch.sh
  release/build.sh
Labels: cla: yes, release-notes-none, size/XS

#619 [release-1.9] Manual CP of #615 - Add GH token
  release/build.sh
Labels: cherrypick/release-1.8, cla: yes, size/XS

#620 [release-1.8] [release-1.9] Manual CP of #615 - Add GH token
  release/build.sh
Labels: cla: yes, release-notes-none, size/XS

#621 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#622 skip istio/envoy in createBranches branching step
  pkg/branch/createBranches.go
Labels: cla: yes, size/XS

#624 Publish 1.9.3
  release/trigger-publish
Labels: cla: yes, size/XS

#625 Publish 1.8.5
  release/trigger-publish
Labels: cla: yes, size/XS

#626 Trigger 1.10.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#627 Trigger second 1.10.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#629 Trigger third 1.10.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#623 Point build.sh back at istio/envoy
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/XS

#630 Trigger a fourth 1.10.0-alpha.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#631 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#628 Trigger publish for 1.10.0-alpha.1
  release/trigger-publish
Labels: cla: yes, size/XS

#632 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#633 Point 1.10 branch to envoyproxy/envoy for envoy commits
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/XS

#634 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#635 Build 1.9.4
  release/trigger-build
Labels: cla: yes, size/XS

#637 Trigger 1.10.0-rc.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#636 Publish 1.9.4
  release/trigger-publish
Labels: cla: yes, size/XS

#638 Trigger 1.10.0-rc.0 publish
  release/trigger-publish
Labels: cla: yes, size/XS
