Repository istio/release-builder, pull requests merged in 2021-07, with the labels that each got.

#686 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#685 Print Error when sanitize charts fails
  pkg/build/build.go
Labels: cla: yes, ok-to-test, size/XS

#689 [release-1.9] Fix timeout retry and don't fail with error if ignoring vulnerabilties
  pkg/build/build.go
  pkg/build/scanner.go
Labels: cla: yes, release-notes-none, size/XS

#690 [release-1.10] Manual cherry pick of #674 to replace github commands with go-git
  go.mod
  go.sum
  licenses/github.com/ProtonMail/go-crypto/LICENSE
  licenses/github.com/emirpasic/gods/LICENSE
  licenses/github.com/go-git/gcfg/LICENSE
  licenses/github.com/go-git/go-billy/v5/LICENSE
  licenses/github.com/go-git/go-git/v5/LICENSE
  licenses/github.com/google/go-github/v35/LICENSE
  licenses/github.com/imdario/mergo/LICENSE
  licenses/github.com/jbenet/go-context/LICENSE
  licenses/github.com/kevinburke/ssh_config/LICENSE
  licenses/github.com/mitchellh/go-homedir/LICENSE
  licenses/github.com/sergi/go-diff/LICENSE
  licenses/github.com/xanzy/ssh-agent/LICENSE
  licenses/gopkg.in/warnings.v0/LICENSE
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/XXL

#684 Branch Enhancements
  example/manifest_branch.yaml
  pkg/model/model.go
  release/branch.sh
Labels: cla: yes, size/XS

#687 Update to use Trivy
  pkg/build/scanner.go
Labels: cla: yes, size/M

#688 [release-1.10] Fix timeout retry and don't fail with error if ignoring vulnerabilties
  pkg/build/build.go
  pkg/build/scanner.go
Labels: cla: yes, release-notes-none, size/XS

#693 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#692 [release-1.9] Update to use Trivy
  pkg/build/scanner.go
Labels: cla: yes, release-notes-none, size/M

#691 [release-1.9] Manual cherry pick of #674 to replace github commands with go-git
  go.mod
  go.sum
  licenses/github.com/ProtonMail/go-crypto/LICENSE
  licenses/github.com/emirpasic/gods/LICENSE
  licenses/github.com/go-git/gcfg/LICENSE
  licenses/github.com/go-git/go-billy/v5/LICENSE
  licenses/github.com/go-git/go-git/v5/LICENSE
  licenses/github.com/google/go-github/v35/LICENSE
  licenses/github.com/imdario/mergo/LICENSE
  licenses/github.com/jbenet/go-context/LICENSE
  licenses/github.com/kevinburke/ssh_config/LICENSE
  licenses/github.com/mitchellh/go-homedir/LICENSE
  licenses/github.com/sergi/go-diff/LICENSE
  licenses/github.com/xanzy/ssh-agent/LICENSE
  licenses/gopkg.in/warnings.v0/LICENSE
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/XXL

#695 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#696 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#697 Add prow private job generation
  pkg/branch/setupProw.go
Labels: cla: yes, size/XS

#694 Update to use Trivy (#687)
  pkg/build/scanner.go
Labels: cla: yes, size/M

#698 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#700 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#701 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#702 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#703 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#704 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#705 Trigger second build for 1.10.3
  release/trigger-build
Labels: cla: yes, size/XS

#707 Add return for successful scan
  pkg/build/scanner.go
Labels: cherrypick/release-1.10, cla: yes, size/S

#708 [release-1.10] Add return for successful scan
  pkg/build/scanner.go
Labels: cla: yes, release-notes-none, size/S

#712 Build release 1.10.3
  release/trigger-build
Labels: cla: yes, size/XS

#709 [release-1.11] Add return for successful scan
  pkg/build/scanner.go
Labels: cla: yes, release-notes-none, size/S

#710 [release-1.11] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: cla: yes, release-notes-none, size/S

#713 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#715 Fix envoy location
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/XS

#716 Fix envoy locatiion
  release/build.sh
  test/publish.sh
Labels: cla: yes, size/XS

#719 trigger 1.11.0-beta.0 bulid (again)
  release/trigger-build
Labels: cla: yes, size/XS

#718 Fix issue where manifest dependencies are SHAs during build
  pkg/branch/branch.go
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: cherrypick/master, cherrypick/release-1.11, cherrypick/release-1.9, cla: yes, size/M

#717 [release-1.9] Add return for successful scan
  pkg/build/scanner.go
Labels: cla: yes, release-notes-none, size/S

#722 trigger 1.11.0-beta.0 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#721 [master] Fix issue where manifest dependencies are SHAs during build
  pkg/branch/branch.go
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/M

#720 [release-1.11] Fix issue where manifest dependencies are SHAs during build
  pkg/branch/branch.go
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/M

#725 Trigger 1.10.3 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#726 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#727 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#729 Build Istio 1.9.7
  release/trigger-build
Labels: cla: yes, size/XS

#728 Trigger beta1 build
  release/trigger-build
Labels: cla: yes, size/XS

#723 [release-1.9] Manual cherry-pick of #721
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: cla: yes, size/M

#730 Publish beta 1
  release/trigger-publish
Labels: cla: yes, size/XS

#731 Rebuild 1.9.7
  release/trigger-build
Labels: cla: yes, size/XS

#732 Publish 1.9.7
  release/trigger-publish
Labels: cla: yes

#733 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#734 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#735 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#736 Trigger beta2 build
  release/trigger-build
Labels: cla: yes, size/XS

#738 Trigger beta2 build
  release/trigger-build
Labels: cla: yes, size/XS

#737 Publish beta2
  release/trigger-publish
Labels: cla: yes

#739 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#740 Trigger beta3 build
  release/trigger-build
Labels: cla: yes, size/XS

#741 Publish beta3
  release/trigger-publish
Labels: cla: yes, size/XS
