Repository istio/release-builder, pull requests merged in 2021-06, with the labels that each got.

#669 Trigger a 1.10.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#670 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#671 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#672 Trigger 1.10.1 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#673 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#676 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#677 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#678 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#679 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: auto-merge, cla: yes, release-notes-none, size/S

#675 Fix timeout retry and don't fail with error if ignoring vulnerabilties
  pkg/build/build.go
  pkg/build/scanner.go
Labels: cla: yes, size/XS

#674 replace github commands with go-git
  go.mod
  go.sum
  licenses/github.com/ProtonMail/go-crypto/LICENSE
  licenses/github.com/emirpasic/gods/LICENSE
  licenses/github.com/go-git/gcfg/LICENSE
  licenses/github.com/go-git/go-billy/v5/LICENSE
  licenses/github.com/go-git/go-git/v5/LICENSE
  licenses/github.com/imdario/mergo/LICENSE
  licenses/github.com/jbenet/go-context/LICENSE
  licenses/github.com/kevinburke/ssh_config/LICENSE
  licenses/github.com/mitchellh/go-homedir/LICENSE
  licenses/github.com/sergi/go-diff/LICENSE
  licenses/github.com/xanzy/ssh-agent/LICENSE
  licenses/gopkg.in/warnings.v0/LICENSE
  pkg/util/git.go
Labels: cla: yes, size/XXL

#681 Release 1.9.6
  release/trigger-publish
Labels: cla: yes, size/XS

#680 Release 1.10.2.
  release/trigger-publish
Labels: cla: yes, size/XS

#682 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#683 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: auto-merge, cla: yes, release-notes-none, size/XS
