Repository istio/release-builder, pull requests merged in 2021-10, with the labels that each got.

#800 Fix build release tag
  pkg/build/docker.go
  pkg/util/command.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#801 Skip validate when version is not semver
  pkg/build/build.go
  pkg/util/command.go
  pkg/validate/validate.go
Labels: cla: yes, size/S

#802 Trigger 1.9.9 build
  release/trigger-build
Labels: cla: yes, size/XS

#806 Fix duplicating tagging in publish
  pkg/publish/docker.go
Labels: cla: yes, size/XS

#799 Add separate flag for building base images
  example/manifest.yaml
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/manifest.go
  pkg/model/model.go
  release/build.sh
  test/publish.sh
Labels: size/M, cla: yes

#805 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#808 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#803 Trigger 1.9.9 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#807 Re build 1.9.9
  release/trigger-build
Labels: cla: yes, size/XS

#809 Fixes to base image builder
  pkg/branch/branch.go
  pkg/build/scanner.go
  pkg/util/files.go
  pkg/util/git.go
Labels: size/M, cla: yes

#810 Trigger build of 1.12.0-alpha.3
  release/trigger-build
Labels: cla: yes, size/XS

#812 Fix base image builder error code
  release/build.sh
Labels: cla: yes, size/XS

#813 Building 1.12.0-alpha.5
  release/trigger-build
Labels: cla: yes, size/XS

#798 Publish 1.12.0-alpha.2
  release/trigger-publish
Labels: cla: yes, size/XS

#814 Republish 1.9.9
  release/trigger-publish
Labels: cla: yes, size/XS

#815 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#820 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none
