Repository istio/release-builder, pull requests merged in 2021-03, with the labels that each got.

#577 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#578 Publish 1.9.1
  release/trigger-publish
Labels: cla: yes, size/XS

#579 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#580 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#582 Update trigger-build
  release/trigger-build
Labels: cla: yes, size/XS

#583 Trigger 1.8.4 build again
  release/trigger-build
Labels: cla: yes, size/XS

#584 Add automated base image creation when base image scan fails
  pkg/build/build.go
  pkg/build/scanner.go
Labels: cla: yes, size/M

#585 Trigger 1.10.0-alpha.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#586 Publish Istio 1.8.4
  release/trigger-publish
Labels: cla: yes, size/XS

#588 [release-1.8] Add automated base image creation when base image scan fails
  pkg/build/build.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/L

#587 [release-1.9] Add automated base image creation when base image scan fails
  pkg/build/build.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/L

#589 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#590 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#591 Build 1.9.2
  release/trigger-build
Labels: cla: yes, size/XS

#593 Retrigger build at Jacob's request
  release/trigger-build
Labels: cla: yes, size/XS

#592 Publish 1.9.2
  release/trigger-publish
Labels: cla: yes, size/XS

#594 Add GitHub token to to allow commits in build subcommand
  pkg/branch/branch.go
  pkg/branch/cmd.go
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/publish/cmd.go
  pkg/util/git.go
Labels: cla: yes, size/M

#595 CP #594 - Add GitHub token to to allow commits in build subcommand
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/publish/cmd.go
  pkg/util/git.go
Labels: cla: yes, size/M

#596 [release-1.8] CP #594 - Add GitHub token to to allow commits in build subcommand
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/scanner.go
  pkg/publish/cmd.go
  pkg/util/git.go
Labels: cla: yes, release-notes-none, size/M
