Repository istio/release-builder, pull requests merged in 2021-08, with the labels that each got.

#742 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, cla: yes, release-notes-none, size/XS

#743 Build RC 1
  release/trigger-build
Labels: cla: yes, size/XS

#744 Build RC 1
  release/trigger-build
Labels: cla: yes, size/XS

#745 Publish RC 1
  release/trigger-publish
Labels: cla: yes, size/XS

#746 Build RC 2
  release/trigger-build
Labels: cla: yes, size/XS

#747 Publish RC 2
  release/trigger-publish
Labels: cla: yes, size/XS

#748 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#749 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#750 Build RC 3
  release/trigger-build
Labels: cla: yes, size/XS

#751 Publish RC 3
  release/trigger-publish
Labels: cla: yes, size/XS

#752 Build RC 4
  release/trigger-build
Labels: cla: yes, size/XS

#753 Publish RC 4
  release/trigger-publish
Labels: cla: yes, size/XS

#754 Automator: update common-files@release-1.9 in istio/release-builder@release-1.9
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#755 Build 1.11.0
  release/trigger-build
Labels: cla: yes, size/XS

#756 Publish 1.11.0
  release/trigger-publish
Labels: cla: yes, size/XS

#758 Rewrite appVersion
  pkg/build/helm.go
Labels: cla: yes, size/XS

#759 Automator: update common-files@release-1.10 in istio/release-builder@release-1.10
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#760 Trigger 1.10.4 build
  release/trigger-build
Labels: cla: yes, size/XS

#761 Sanitize istiod-remote charts
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: cla: yes, size/XS, cherrypick/release-1.11

#762 [release-1.11] Sanitize istiod-remote charts
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: cla: yes, size/XS, release-notes-none

#763 Release 1.10.4
  release/trigger-publish
Labels: cla: yes, size/XS

#764 Publish 1.11.1
  release/trigger-publish
Labels: cla: yes, size/XS

#765 Trigger 1.9.8 publish
  release/trigger-publish
Labels: cla: yes, size/XS

#767 Trigger 1.11.2 build
  release/trigger-build
Labels: cla: yes, size/XS, release-notes-none

#768 Retregger 1.11.2
  release/trigger-build
Labels: cla: yes, size/XS

#769 Build 1.11.2
  release/trigger-build
Labels: cla: yes, size/XS
