Repository istio/release-builder, pull requests merged in 2021-11, with the labels that each got.

#829 [release-1.12] Trigger another beta.0 build
  release/trigger-build
Labels: cla: yes, size/XS

#830 [release-1.12] Trigger publish of 1.12-beta.0
  release/trigger-publish
Labels: cla: yes, size/XS

#831 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#832 Add version prefix to base image tag
  pkg/build/scanner.go
Labels: cla: yes, size/S, cherrypick/release-1.12

#834 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#835 Remove obsolete gen-charts target
  pkg/build/archive.go
  pkg/build/docker.go
Labels: cla: yes, size/XS

#833 [release-1.12] Add version prefix to base image tag
  pkg/build/scanner.go
Labels: cla: yes, size/S, release-notes-none

#836 Trigger 1.12.0-beta.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#837 Publish 1.12-beta.1
  release/trigger-publish
Labels: cla: yes, size/XS

#838 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#840 Automator: update common-files@release-1.12 in istio/release-builder@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#841 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#839 Trigger 1.12.0-beta.2
  release/trigger-build
Labels: cla: yes, size/XS

#842 Publish 1.12.0-beta.2
  release/trigger-publish
Labels: cla: yes, size/XS

#843 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, cla: yes, auto-merge, release-notes-none

#844 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#845 Trigger a build for 1.12.0-rc.0
  release/trigger-build
Labels: cla: yes, size/XS

#849 Automator: update common-files@release-1.12 in istio/release-builder@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#848 Trigger 1.12.0-rc.1 build
  release/trigger-build
Labels: cla: yes, size/XS

#850 Publish 1.12.0-rc.1
  release/trigger-publish
Labels: cla: yes, size/XS

#852 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: cla: yes, size/S, auto-merge, release-notes-none

#851 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#853 1.12.0 release build
  release/trigger-build
Labels: cla: yes, size/XS

#854 Publish 1.12.0 release build
  release/trigger-publish
Labels: cla: yes, size/XS

#847 Trigger 1.10.6 build
  release/trigger-build
Labels: cla: yes

#857 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#858 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: cla: yes, size/XS, auto-merge, release-notes-none

#856 Trigger second 1.10.6 build
  release/trigger-build
Labels: cla: yes, size/XS

#859 Trigger third release 1.10.6 build
  release/trigger-build
Labels: cla: yes, size/XS

#860 Trigger 1.11.5 build
  release/trigger-build
Labels: cla: yes, size/XS
