Repository istio/release-builder, pull requests merged in 2022-10, with the labels that each got.

#1212 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1213 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1214 trigger 1.14.5 build
  release/trigger-build
Labels: size/XS

#1216 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1215 Trigger 1.15.2 Build
  release/trigger-build
Labels: size/XS

#1219 Trigger the build for Istio 1.13.9
  release/trigger-build
Labels: size/XS

#1223 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1224 Trigger a new build for Istio 1.14.5
  release/trigger-build
Labels: size/XS

#1222 Trigger a new build for Istio 1.13.9
  release/trigger-build
Labels: size/XS

#1226 Retrigger 1.15.2 build
  release/trigger-build
Labels: size/XS

#1227 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1217 Trigger publish of Istio 1.14.5
  release/trigger-publish
Labels: size/XS

#1228 Trigger publish of 1.15.2
  release/trigger-publish
Labels: size/XS

#1229 helm publish: disable caching
  pkg/publish/gcs.go
Labels: size/XS, cherrypick/release-1.13, cherrypick/release-1.14, cherrypick/release-1.15

#1232 [release-1.15] helm publish: disable caching
  pkg/publish/gcs.go
Labels: size/XS, release-notes-none

#1230 [release-1.13] helm publish: disable caching
  pkg/publish/gcs.go
Labels: size/XS, release-notes-none

#1233 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1234 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1235 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1237 Test - Add semver err to log
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  pkg/util/command.go
Labels: size/XS

#1239 [release-1.15] Build 1.15.3
  release/trigger-build
Labels: size/XS

#1240 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1241 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#1242 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1246 Manual update-common
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS

#1247 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1248 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/gobuild.sh
Labels: size/XS, auto-merge, release-notes-none

#1244 Trigger 1.16.0-beta.0 publish
  release/trigger-publish
Labels: size/XS

#1249 Update dependencies
  go.mod
  go.sum
  licenses/github.com/googleapis/go-type-adapters/LICENSE
  licenses/go.uber.org/multierr/LICENSE.txt
  licenses/istio.io/pkg/LICENSE
Labels: size/XXL

#1250 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1251 [release-1.16] trigger 1.16.0 beta1 build
  release/trigger-build
Labels: size/XS

#1252 [release-1.16] Trigger 1.16.0 beta.1 publish
  release/trigger-publish
Labels: size/XS

#1255 make deb/rpm support multi arch
  pkg/build/debian.go
  pkg/build/rpm.go
  pkg/model/model.go
Labels: size/M

#1257 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1258 [release-1.16] make deb/rpm support multi arch
  pkg/build/debian.go
  pkg/build/rpm.go
  pkg/model/model.go
Labels: size/M, release-notes-none

#1254 fix-publish-vars
  release/publish.sh
Labels: size/XS, ok-to-test

#1260 [release-1.16] trigger 1.16.0-beta.2 build
  release/trigger-build
Labels: size/XS

#1261 [release-1.16] Trigger 1.16.0 beta.2 publish
  release/trigger-publish
Labels: size/XS

#1262 [release-1.15] make deb/rpm support multi arch
  pkg/build/debian.go
  pkg/build/rpm.go
  pkg/model/model.go
Labels: size/M, release-notes-none

#1256 Trigger 1.15.3 publish
  release/trigger-publish
Labels: size/XS
