Repository istio/release-builder, pull requests merged in 2022-09, with the labels that each got.

#1183 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1186 Trigger the build for release 1.13.8
  release/trigger-build
Labels: size/XS

#1188 Trigger a new build for Istio 1.14.4 release
  release/trigger-build
Labels: size/XS

#1189 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1193 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1194 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1191 Trigger a new build for release 1.13.8
  release/trigger-build
Labels: size/XS

#1190 Trigger a new build for Istio 1.14.4 release
  release/trigger-build
Labels: size/XS

#1195 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1196 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1185 Trigger the publish of release 1.14.4
  release/trigger-publish
Labels: size/XS

#1187 Trigger the publish of release 1.13.8
  release/trigger-publish
Labels: size/XS

#1197 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1198 More debugging for helm publish
  pkg/publish/gcs.go
  pkg/publish/helm.go
Labels: size/M, cherrypick/release-1.14, cherrypick/release-1.15

#1199 [release-1.14] More debugging for helm publish
  pkg/publish/gcs.go
  pkg/publish/helm.go
Labels: size/M, release-notes-none

#1200 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1201 Trigger 1.15.1 build
  release/trigger-build
Labels: size/XS

#1202 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1203 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#1204 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1205 Retrigger 1.15.1 build
  release/trigger-build
Labels: size/XS

#1206 Trigger Publish of 1.15.1
  release/trigger-publish
Labels: size/XS

#1207 Update Release Notes URL
  pkg/publish/github.go
Labels: cherrypick/release-1.13, cherrypick/release-1.14, cherrypick/release-1.15

#1209 [release-1.14] Update Release Notes URL
  pkg/publish/github.go
Labels: size/XS, release-notes-none

#1208 [release-1.13] Update Release Notes URL
  pkg/publish/github.go
Labels: size/XS, release-notes-none

#1210 [release-1.15] Update Release Notes URL
  pkg/publish/github.go
Labels: size/XS, release-notes-none

#1211 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
