Repository istio/release-builder, pull requests merged in 2022-02, with the labels that each got.

#917 Trigger 1.11.6 build
  release/trigger-build
Labels: size/XS

#918 Trigger 1.11.6 build
  release/trigger-build
Labels: size/XS

#919 Trigger 1.11.6 build
  release/trigger-build
Labels: size/XS

#920 Trigger 1.11.6 build
  release/trigger-build
Labels: size/XS

#921 Trigger 1.11.6 build
  release/trigger-build
Labels: size/XS

#922 trigger build: 1.13.0-beta.1
  release/trigger-build
Labels: size/XS

#923 trigger publish: 1.13.0-beta.1
  release/trigger-publish
Labels: size/XS

#924 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#925 Publish 1.11.6
  release/trigger-publish
Labels: size/XS

#893 Generate SBOM for istio repository
  pkg/build/build.go
  pkg/build/sbom.go
Labels: size/M, cherrypick/release-1.13

#926 Update the dry-run version for main branch to 1.14
  test/publish.sh
Labels: size/XS

#928 Make bom log-level to error
  pkg/build/sbom.go
Labels: size/XS

#929 Trigger build for 1.12.3
  release/trigger-build
Labels: size/XS

#932 Automator: update common-files@release-1.12 in istio/release-builder@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#933 build 1.13.0
  release/trigger-build
Labels: size/XS

#934 build 1.13.0
  release/trigger-build
Labels: size/XS

#938 Automator: update common-files@release-1.13 in istio/release-builder@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#927 [release-1.13] Generate SBOM for istio repository
  pkg/build/build.go
  pkg/build/sbom.go
Labels: size/M, release-notes-none

#939 Publish 1.13.0 release build
  release/trigger-publish
Labels: size/XS

#941 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#942 Automator: update common-files@release-1.12 in istio/release-builder@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#943 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#944 Push base image as latest
  pkg/build/scanner.go
Labels: size/XS

#946 Publish 1.12.4
  release/trigger-publish
Labels: size/XS

#947 Publish 1.13.1
  release/trigger-publish
Labels: size/XS

#950 build: do not require github token
  pkg/build/build.go
  pkg/build/cmd.go
  release/build.sh
Labels: size/S

#951 [release-1.13] build: do not require github token
  pkg/build/build.go
  pkg/build/cmd.go
  release/build.sh
Labels: size/S, release-notes-none

#952 Refine build dependencies
  release/build.sh
  release/publish.sh
Labels: size/M, cherrypick/release-1.11, cherrypick/release-1.12, cherrypick/release-1.13

#954 [release-1.13] Refine build dependencies
  release/build.sh
  release/publish.sh
Labels: size/M, release-notes-none

#953 [release-1.12] Refine build dependencies
  release/build.sh
  release/publish.sh
Labels: size/M, release-notes-none

#955 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#958 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#959 Fixing error check in SBOM (can segfault if not handled).
  pkg/build/sbom.go
Labels: size/XS, cherrypick/release-1.13

#960 [release-1.13] Fixing error check in SBOM (can segfault if not handled).
  pkg/build/sbom.go
Labels: size/XS, release-notes-none

#957 [release-1.11] build: do not require github token
  pkg/build/build.go
  pkg/build/cmd.go
  release/build.sh
Labels: size/S

#961 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#956 [release-1.12] build: do not require github token
  pkg/build/build.go
  pkg/build/cmd.go
  release/build.sh
Labels: size/S, release-notes-none

#962 Automator: update common-files@release-1.12 in istio/release-builder@release-1.12
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#964 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
