Repository istio/release-builder, pull requests merged in 2022-04, with the labels that each got.

#1017 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1018 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1019 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1020 Fix helm chart changes changing latest to release
  pkg/build/helm.go
Labels: size/S, cherrypick/master

#1021 [master] Fix helm chart changes changing latest to release
  pkg/build/helm.go
Labels: size/S, release-notes-none

#1013 Publish 1.12.6
  release/trigger-publish
Labels: size/XS

#1023 replace golint with revive
  pkg/model/model.go
Labels: size/XS

#1024 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1027 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1028 Automator: update common-files@release-1.13 in istio/release-builder@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1030 build 1.13.3
  release/trigger-build
Labels: size/XS

#1031 clean golint
  pkg/model/model.go
Labels: size/XS

#1032 trigger publish 1.13.3
  release/trigger-publish
Labels: size/XS

#1033 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1034 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1035 fix automation step 3: run prowgen from wd
  .gitignore
  pkg/branch/setupProw.go
Labels: size/S

#1037 [release-1.14] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/M, release-notes-none

#1038 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1039 [release-1.14] Move UPDATE_BRANCH to release-1.14
  common/Makefile.common.mk
Labels: size/XS

#1040 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1041 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1042 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#1043 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1044 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#1045 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1046 scanner: do not panic when there is no error
  pkg/build/scanner.go
Labels: size/S

#1047 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#1048 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1049 trigger a 1.14 alpha build
  release/trigger-build
Labels: size/XS

#1050 Always run scripts from repo root
  release/build.sh
  release/publish.sh
Labels: size/XS
