Repository istio/release-builder, pull requests merged in 2022-12, with the labels that each got.

#1295 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1298 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1299 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1296 Trigger a build for Istio 1.14.6
  release/trigger-build
Labels: size/XS

#1300 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1305 [release-1.14] Retrigger 1.14.6 build
  release/trigger-build
Labels: size/XS

#1293 [release-1.16] trigger 1.16.1 build
  release/trigger-build
Labels: size/XS

#1301 [release-1.15] trigger 1.15.4 build
  release/trigger-build
Labels: size/XS

#1302 [release-1.15] Trigger 1.15.4 publish
  release/trigger-publish
Labels: size/XS

#1303 [release-1.16] Trigger 1.16.1 publish
  release/trigger-publish
Labels: size/XS

#1297 Trigger publish of Istio 1.14.6
  release/trigger-publish
Labels: size/XS

#1306 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1307 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1308 Automator: update common-files@master in istio/release-builder@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1309 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1310 Automator: update common-files@master in istio/release-builder@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1311 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1312 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1313 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1314 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1315 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1318 Update common-files and fix lint
  common/.commonfiles.sha
  common/scripts/setup_env.sh
  release/build.sh
Labels: size/XS

#1320 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1319 update-testpublish
  release/build.sh
  test/publish.sh
Labels: size/M

#1321 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
