Repository istio/release-builder, pull requests merged in 2022-05, with the labels that each got.

#1051 Trigger 1.12.7 build
  release/trigger-build
Labels: size/XS

#1054 Automator: update common-files@master in istio/release-builder@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1053 build another alpha candidate
  release/trigger-build
Labels: size/XS

#1055 trigger publish of alpha 1.14
  release/trigger-publish
Labels: size/XS

#1057 [release-1.14] helm repo: push only to GCR
  release/publish.sh
Labels: size/XS, release-notes-none

#1058 Update cosign flag
  pkg/publish/cmd.go
  pkg/publish/docker.go
Labels: size/XS, cherrypick/release-1.14

#1059 [release-1.14] Update cosign flag
  pkg/publish/cmd.go
  pkg/publish/docker.go
Labels: size/XS, release-notes-none

#1060 retrigger alpha publish
  release/trigger-publish
Labels: size/XS

#1052 Publish 1.12.7
  release/trigger-publish
Labels: size/XS

#1062 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1063 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
Labels: size/XS, auto-merge, release-notes-none

#1064 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1065 Build 1.14.beta.0
  release/trigger-build
Labels: size/XS

#1066 Automator: update common-files@release-1.13 in istio/release-builder@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1067 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1068 build 1.13.4
  release/trigger-build
Labels: size/XS

#1069 Trigger publish of 1.14.0.beta
  release/trigger-publish
Labels: size/XS

#1070 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1071 build 1.13.4
  release/trigger-build
Labels: size/XS

#1072 publish 1.13.4
  release/trigger-publish
Labels: size/XS

#1073 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1074 Trigger build of release 1.14.0-beta.1
  release/trigger-build
Labels: size/XS

#1076 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1075 Publish release 1.14.0.beta.1
  release/trigger-publish
Labels: size/XS

#1077 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1079 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  pkg/util/git.go
Labels: size/S, auto-merge, release-notes-none

#1080 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/XS, auto-merge, release-notes-none

#1081 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#1082 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1083 Build release 1.14.0
  release/trigger-build
Labels: size/XS

#1085 Rebuild the 1.14.0
  release/trigger-build
Labels: size/XS

#1088 rebuild 1.14.0
  release/trigger-build
Labels: size/XS
