Repository istio/release-builder, pull requests merged in 2022-03, with the labels that each got.

#963 Converting SBOM error into warning -- lack of BOM should not be fatal.
  pkg/build/build.go
  pkg/model/model.go
Labels: size/S, cherrypick/release-1.13

#965 [release-1.13] Converting SBOM error into warning -- lack of BOM should not be fatal.
  pkg/build/build.go
  pkg/model/model.go
Labels: size/S, release-notes-none

#966 Support labels on PR creation and add auto-merge to base image PR
  pkg/branch/branch.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: size/S, cherrypick/release-1.12, cherrypick/release-1.13

#968 [release-1.13] Support labels on PR creation and add auto-merge to base image PR
  pkg/branch/branch.go
  pkg/build/scanner.go
  pkg/util/git.go
Labels: size/S, release-notes-none

#969 Trigger 1.12.5 build
  release/trigger-build
Labels: size/XS

#971 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#972 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#978 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#979 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#980 Automator: update common-files@release-1.13 in istio/release-builder@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#981 Automator: update common-files@release-1.12 in istio/release-builder@release-1.12
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#982 Automator: update common-files@release-1.11 in istio/release-builder@release-1.11
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#975 [release-1.12] Re build 1.12.5
  release/trigger-build
Labels: size/XS

#976 Build 1.13.2
  release/trigger-build
Labels: size/XS

#973 Build 1.11.8
  release/trigger-build
Labels: size/XS

#983 Update trivy usage after version update
  pkg/build/scanner.go
Labels: size/XS

#984 [release-1.11] rebuild 1.11.8
  release/trigger-build
Labels: size/XS

#986 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#987 Trigger 1.11.8 build
  release/trigger-build
Labels: size/XS

#988 Trigger 1.13.2 build
  release/trigger-build
Labels: size/XS

#977 Publish 1.13.2
  release/trigger-publish
Labels: size/XS

#970 Publish 1.12.5
  release/trigger-publish
Labels: size/XS

#974 Publish 1.11.8
  release/trigger-publish
Labels: size/XS

#991 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#992 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#993 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/S, auto-merge, release-notes-none

#994 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#996 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#995 Generate the license tar for release-builder
  example/manifest.yaml
  pkg/validate/validate.go
  release/build.sh
  test/publish.sh
Labels: size/S

#997 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#998 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#999 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/L, auto-merge, release-notes-none

#1000 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1002 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1003 Remove gogo-genproto
  README.md
  example/manifest.yaml
  example/manifest_branch.yaml
  pkg/model/model.go
  pkg/validate/validate.go
  release/branch.sh
  release/build.sh
  test/publish.sh
Labels: size/S

#1005 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1006 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: auto-merge, release-notes-none

#1007 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1008 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1009 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1010 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1011 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1012 Trigger 1.12.6 build
  release/trigger-build
Labels: size/XS

#1014 Unset FOR_BUILD_CONTAINER so `make` happens in manifest directories
  pkg/util/command.go
Labels: size/XS

#1015 README updates for branch cutting
  README.md
  release/trigger-branch
Labels: size/M

#1016 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
