Repository istio/release-builder, pull requests merged in 2022-08, with the labels that each got.

#1145 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1137 Trigger the publish of 1.13.7
  release/trigger-publish
Labels: size/XS

#1146 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1149 [release-1.15] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/M, release-notes-none

#1151 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1150 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1152 [release-1.15] Update common files from release-1.15 branch
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS

#1153 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1154 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1155 Support publishing multi-arch images
  go.mod
  go.sum
  licenses/cloud.google.com/go/compute/LICENSE
  licenses/cloud.google.com/go/iam/LICENSE
  licenses/github.com/containerd/stargz-snapshotter/estargz/LICENSE
  licenses/github.com/docker/cli/LICENSE
  licenses/github.com/docker/distribution/LICENSE
  licenses/github.com/docker/docker-credential-helpers/LICENSE
  licenses/github.com/docker/docker/LICENSE
  licenses/github.com/docker/docker/contrib/busybox/LICENSE
  licenses/github.com/docker/go-connections/LICENSE
  licenses/github.com/docker/go-units/LICENSE
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/github.com/google/go-containerregistry/LICENSE
  licenses/github.com/google/uuid/LICENSE
  licenses/github.com/googleapis/enterprise-certificate-proxy/LICENSE
  licenses/github.com/googleapis/go-type-adapters/LICENSE
  licenses/github.com/klauspost/compress/LICENSE
  licenses/github.com/klauspost/compress/gzhttp/LICENSE
  licenses/github.com/klauspost/compress/internal/snapref/LICENSE
  licenses/github.com/klauspost/compress/s2/LICENSE
  licenses/github.com/klauspost/compress/s2/cmd/internal/filepathx/LICENSE
  licenses/github.com/klauspost/compress/s2/cmd/internal/readahead/LICENSE
  licenses/github.com/klauspost/compress/snappy/LICENSE
  licenses/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt
  licenses/github.com/opencontainers/go-digest/LICENSE
  licenses/github.com/opencontainers/image-spec/LICENSE
  licenses/github.com/pkg/errors/LICENSE
  licenses/github.com/sirupsen/logrus/LICENSE
  licenses/github.com/vbatts/tar-split/LICENSE
  pkg/branch/branch.go
  pkg/build/build.go
  pkg/build/grafana.go
  pkg/build/helm.go
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/cmd.go
  pkg/publish/docker.go
  pkg/publish/gcs.go
  pkg/publish/github.go
  pkg/publish/grafana.go
  pkg/publish/helm.go
  pkg/util/command.go
  pkg/util/files.go
  pkg/util/git.go
  pkg/validate/validate.go
Labels: size/XXL

#1156 helm publish: dump versions
  pkg/publish/helm.go
Labels: size/M, cherrypick/release-1.13, cherrypick/release-1.14

#1158 [release-1.14] helm publish: dump versions
  pkg/publish/helm.go
Labels: size/M, release-notes-none

#1159 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1160 Update in-repo config to use architectures
  example/manifest.yaml
  release/build.sh
Labels: size/XS

#1157 [release-1.15] Support publishing multi-arch images
  go.mod
  go.sum
  licenses/cloud.google.com/go/compute/LICENSE
  licenses/cloud.google.com/go/iam/LICENSE
  licenses/github.com/containerd/stargz-snapshotter/estargz/LICENSE
  licenses/github.com/docker/cli/LICENSE
  licenses/github.com/docker/distribution/LICENSE
  licenses/github.com/docker/docker-credential-helpers/LICENSE
  licenses/github.com/docker/docker/LICENSE
  licenses/github.com/docker/docker/contrib/busybox/LICENSE
  licenses/github.com/docker/go-connections/LICENSE
  licenses/github.com/docker/go-units/LICENSE
  licenses/github.com/gogo/protobuf/LICENSE
  licenses/github.com/google/go-containerregistry/LICENSE
  licenses/github.com/google/uuid/LICENSE
  licenses/github.com/googleapis/enterprise-certificate-proxy/LICENSE
  licenses/github.com/googleapis/go-type-adapters/LICENSE
  licenses/github.com/klauspost/compress/LICENSE
  licenses/github.com/klauspost/compress/gzhttp/LICENSE
  licenses/github.com/klauspost/compress/internal/snapref/LICENSE
  licenses/github.com/klauspost/compress/s2/LICENSE
  licenses/github.com/klauspost/compress/s2/cmd/internal/filepathx/LICENSE
  licenses/github.com/klauspost/compress/s2/cmd/internal/readahead/LICENSE
  licenses/github.com/klauspost/compress/snappy/LICENSE
  licenses/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt
  licenses/github.com/opencontainers/go-digest/LICENSE
  licenses/github.com/opencontainers/image-spec/LICENSE
  licenses/github.com/pkg/errors/LICENSE
  licenses/github.com/sirupsen/logrus/LICENSE
  licenses/github.com/vbatts/tar-split/LICENSE
  pkg/branch/branch.go
  pkg/build/build.go
  pkg/build/grafana.go
  pkg/build/helm.go
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/cmd.go
  pkg/publish/docker.go
  pkg/publish/gcs.go
  pkg/publish/github.go
  pkg/publish/grafana.go
  pkg/publish/helm.go
  pkg/util/command.go
  pkg/util/files.go
  pkg/util/git.go
  pkg/validate/validate.go
Labels: size/XXL, release-notes-none

#1162 [release-1.15] Update in-repo config to use architectures
  example/manifest.yaml
  release/build.sh
Labels: size/XS, release-notes-none

#1161 Trigger 1.15-beta.0 build
  release/trigger-build
Labels: size/XS

#1163 Trigger 1.15-beta.0 publish
  release/trigger-publish
Labels: size/XS

#1164 Trigger release 1.15.0-beta.0 build
  release/trigger-build
Labels: size/XS

#1165 Trigger release 1.15.0-beta.0 publish
  release/trigger-publish
Labels: size/XS

#1166 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1167 Automator: update common-files@release-1.14 in istio/release-builder@release-1.14
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1168 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1169 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1170 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1171 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#1174 Automator: update common-files@release-1.13 in istio/release-builder@release-1.13
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1172 trigger 1.15.0-beta.1 build
  release/trigger-build
Labels: size/XS

#1173 trigger 1.15.0-beta.1 publish
  release/trigger-publish
Labels: size/XS

#1176 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1175 Trigger release 1.15.0 build
  release/trigger-build
Labels: size/XS

#1177 Retrigger 1.15.0-rc.0 build
  release/trigger-build
Labels: size/XS

#1178 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1179 [release-1.15.0] Publish 1.15.0-rc.0
  release/trigger-publish
Labels: size/XS

#1180 Trigger release 1.15.0 build
  release/trigger-build
Labels: size/XS

#1182 Retrigger 1.15.0 build
  release/trigger-build
Labels: size/XS

#1181 Trigger release 1.15.0 publish
  release/trigger-publish
Labels: size/XS
