Repository istio/release-builder, pull requests merged in 2023-10, with the labels that each got.

#1642 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none

#1643 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1644 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1645 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1646 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1647 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1649 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1651 Trigger publish for 1.17.7
  release/trigger-publish
Labels: size/XS

#1652 Trigger publish for 1.18.4
  release/trigger-publish
Labels: size/XS

#1653 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1654 Update trigger-publish
  release/trigger-publish
Labels: size/XS

#1656 Update golang.org/x/net
  go.mod
  go.sum
Labels: size/M

#1661 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1664 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1665 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1666 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1659 Trigger build for 1.19.3
  release/trigger-build
Labels: size/XS

#1658 Trigger build for 1.18.5
  release/trigger-build
Labels: size/XS

#1657 Trigger build for 1.17.8
  release/trigger-build
Labels: size/XS

#1662 Trigger publish 1 18 5
  release/trigger-publish
Labels: size/XS

#1667 Update base image code to check correct base image
  release/build-base-images.sh
Labels: size/XS

#1668 Remove envoy dependency in step 1
  release/branch.sh
Labels: size/XS

#1670 [release-1.20] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S

#1672 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1674 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1675 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1676 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1677 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1673 [release-1.20] Trigger a 1.20.0-beta.0 build
  release/trigger-build
Labels: size/XS

#1678 [release-1.20] Trigger a publish of 1.20.0-beta.0
  release/trigger-publish
Labels: size/XS

#1679 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1680 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1681 [release-1.20] Update build-base-images to use 1.20 branch
  release/build-base-images.sh
Labels: size/XS

#1684 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1682 [release-1.20] trigger 1.20.0 beta.1 build
  release/trigger-build
Labels: size/XS

#1686 Automator: update common-files@master in istio/release-builder@master
  LICENSE
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
