Repository istio/release-builder, pull requests merged in 2023-09, with the labels that each got.

#1621 Trigger build for 1.19.0
  release/trigger-build
Labels: size/XS, release-notes-none

#1622 Trigger publish for 1.19.0
  release/trigger-publish
Labels: size/XS, release-notes-none

#1627 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1628 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1629 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1630 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1631 [1.18.3] Release 1.18.3
  release/trigger-publish
Labels: size/XS

#1632 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1633 TagRepo(): Explicitly do not sign
  pkg/source.go
Labels: size/XS

#1635 Update dependencies and move go.mod to match istio/istio
  go.mod
  go.sum
  licenses/cloud.google.com/go/longrunning/LICENSE
  licenses/dario.cat/mergo/LICENSE
  licenses/github.com/cyphar/filepath-securejoin/LICENSE
  licenses/go.uber.org/atomic/LICENSE.txt
  licenses/golang.org/x/mod/LICENSE
  licenses/google.golang.org/genproto/googleapis/api/LICENSE
  licenses/google.golang.org/genproto/googleapis/rpc/LICENSE
  pkg/util/files.go
Labels: size/XXL

#1637 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1636 Trigger release-1.17.6 publish
  release/trigger-publish
Labels: size/XS

#1638 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1639 Trigger build for 1.19.1
  release/trigger-build
Labels: size/XS

#1640 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
Labels: size/S, auto-merge, release-notes-none
