Repository istio/release-builder, pull requests merged in 2023-02, with the labels that each got.

#1365 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1367 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1368 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1369 build a new beta off of go 1.20
  release/trigger-build
Labels: size/XS

#1370 publish a new beta off of go 1.20
  release/trigger-publish
Labels: size/XS

#1371 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1372 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1373 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1374 [release-1.17] Trigger 1.17.0-rc.0 build
  release/trigger-build
Labels: size/XS

#1377 [release-1.17] Retrigger the 1.17.0-rc.0 build
  release/trigger-build
Labels: size/XS

#1379 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1381 [release-1.17] Trigger a 1.17.0 build
  release/trigger-build
Labels: size/XS

#1380 [release-1.17] Publish 1.17.0
  release/trigger-publish
Labels: size/XS

#1383 Fix helm hub release
  release/publish.sh
Labels: size/XS, cherrypick/master

#1384 [master] Fix helm hub release
  release/publish.sh
Labels: size/XS, release-notes-none

#1385 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1386 fix gcr mirror
  release/publish.sh
Labels: size/XS, cherrypick/master

#1387 [master] fix gcr mirror
  release/publish.sh
Labels: size/XS, release-notes-none

#1388 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1389 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1390 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1391 Trigger Build 1.16.3
  release/trigger-build
Labels: size/XS

#1394 Trigger Build 1.15.6
  release/trigger-build
Labels: size/XS

#1396 Trigger build of 1.17.1
  release/trigger-build
Labels: size/XS

#1398 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1401 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1403 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1393 Trigger Publish 1.16.3
  release/trigger-publish
Labels: size/XS

#1395 Trigger Publish 1.15.6
  release/trigger-publish
Labels: size/XS

#1402 [release-1.17] Retrigger a 1.17.1 build
  release/trigger-build
Labels: size/XS

#1405 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1406 Use architecture environment variable for scanner
  pkg/build/scanner.go
Labels: size/S

#1407 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1408 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1397 Trigger publish of 1.17.1
  release/trigger-publish
Labels: size/XS

#1400 Add ztunnel as a release artifact
  README.md
  example/manifest.yaml
  example/manifest_branch.yaml
  pkg/build/helm.go
  pkg/model/model.go
  pkg/validate/validate.go
  release/branch.sh
  release/build.sh
  test/publish.sh
Labels: size/M

#1410 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS, auto-merge, release-notes-none

#1409 Trim brackets if they are included in `ARCH`
  release/build.sh
  test/publish.sh
Labels: size/S

#1411 Trigger build of 1.18.0-alpha.0
  release/trigger-build
Labels: size/XS
