Repository istio/release-builder, pull requests merged in 2023-03, with the labels that each got.

#1413 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1414 Trigger build of 1.18.0-alpha.1
  release/trigger-build
Labels: size/XS

#1416 Automator: update common-files@master in istio/release-builder@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1415 fix cosign command for 2.0
  pkg/publish/docker.go
Labels: size/XS

#1417 Rebuild Trigger build of 1.18.0-alpha.1
  release/trigger-build
Labels: size/XS

#1418 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1419 Trigger build of 1.18.0-alpha.2
  release/trigger-build
Labels: size/XS

#1420 Trigger build of 1.18.0-alpha.0, again
  release/trigger-build
Labels: size/XS

#1412 Publish 1.18.0-alpha.0
  release/trigger-publish
Labels: size/XS

#1421 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1422 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1424 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1426 [release-1.17] Trigger 1.17.2 build
  release/trigger-build
Labels: size/XS, release-notes-none

#1428 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1429 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/M, auto-merge, release-notes-none

#1431 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1432 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1433 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1434 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1435 Use `ISTIO_BASE_REGISTRY` to scan base image when it is set
  pkg/build/scanner.go
Labels: size/XS

#1436 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1437 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/metallb.yaml
Labels: size/L, auto-merge, release-notes-none

#1439 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: size/L, auto-merge, release-notes-none
