Repository istio/release-builder, pull requests merged in 2023-08, with the labels that each got.

#1598 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1599 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1602 [release-1.19] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S

#1603 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1604 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1605 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1606 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1608 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1609 [release-1.19] Trigger a 1.19-beta.0 build
  release/trigger-build
Labels: size/XS

#1611 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1612 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1610 Trigger publish for beta.0
  release/trigger-publish
Labels: size/XS

#1613 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1614 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1615 Trigger build for beta.1
  release/trigger-build
Labels: size/XS

#1616 Trigger publish for beta.1
  release/trigger-publish
Labels: size/XS

#1617 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1618 Trigger build for rc.0
  release/trigger-build
Labels: release-notes-none

#1620 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1619 Trigger publish for rc.0
  release/trigger-publish
Labels: size/XS, release-notes-none

#1623 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1624 [1.18.3] Trigger 1.18.3 build
  release/trigger-build
Labels: size/XS

#1625 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
