Repository istio/release-builder, pull requests merged in 2023-04, with the labels that each got.

#1442 trigger 1.15.7 publish
  release/trigger-publish
Labels: size/XS

#1443 trigger 1.16.4 publish
  release/trigger-publish
Labels: size/XS

#1446 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1447 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/S, auto-merge, release-notes-none

#1448 Manual update of common-files
  common/.commonfiles.sha
  common/Makefile.common.mk
Labels: size/XS

#1449 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1450 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1451 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1452 Update various go modules
  go.mod
  go.sum
  licenses/cloud.google.com/go/compute/metadata/LICENSE
  licenses/cloud.google.com/go/longrunning/LICENSE
  licenses/github.com/google/s2a-go/LICENSE.md
  licenses/github.com/klauspost/compress/internal/lz4ref/LICENSE
  licenses/google.golang.org/appengine/LICENSE
Labels: size/XXL

#1453 Update deps 2023-04-10
  go.mod
  go.sum
  licenses/gopkg.in/natefinch/lumberjack.v2/LICENSE
Labels: size/L

#1456 drop kustomize from helm chart
  pkg/build/helm.go
Labels: cherrypick/release-1.16, cherrypick/release-1.17

#1455 Fix cosign signing
  pkg/publish/docker.go
Labels: size/XS

#1459 [release-1.17] drop kustomize from helm chart
  pkg/build/helm.go
Labels: size/S, release-notes-none

#1458 [release-1.16] drop kustomize from helm chart
  pkg/build/helm.go
Labels: size/S, release-notes-none

#1457 Using digests rather than image tags for cosign signatures.
  pkg/publish/docker.go
Labels: size/M

#1461 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1462 Triggering alpha build to test new release-builder code.
  release/trigger-build
Labels: size/XS

#1466 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1469 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1468 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
