Repository istio/release-builder, pull requests merged in 2023-05, with the labels that each got.

#1470 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1471 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1474 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1476 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1477 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1478 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1479 [1.18-beta.1 Step 2] Trigger 1.18-beta.1 build
  release/trigger-build
Labels: size/XS, release-notes-none

#1480 [1.18-beta.1 Step 3] Trigger 1.18-beta.1 publish
  release/trigger-publish
Labels: size/XS, release-notes-none

#1481 [CNCF graduation] Add security tab for Istio repos
  .github/SECURITY.md
Labels: size/XS

#1482 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1483 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1486 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1487 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1489 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1490 Trigger build of 1.16.5
  release/trigger-build
Labels: size/XS

#1491 Trigger Publish for 1.16.5
  release/trigger-publish
Labels: size/XS

#1493 Fix dry-run test (remove pkg as it's no longer used)
  README.md
  example/manifest.yaml
  example/manifest_branch.yaml
  go.mod
  go.sum
  licenses/istio.io/istio/LICENSE
  pkg/branch/branch.go
  pkg/branch/cmd.go
  pkg/branch/createBranches.go
  pkg/branch/createToolImages.go
  pkg/branch/istioReleaseBuilderUpdates.go
  pkg/branch/setupProw.go
  pkg/branch/stopPublishingLatest.go
  pkg/branch/updateCodeOwners.go
  pkg/branch/updateCommonFiles.go
  pkg/branch/updateCommonFilesCommon.go
  pkg/branch/updateDependencies.go
  pkg/build/build.go
  pkg/build/cmd.go
  pkg/build/helm.go
  pkg/build/sbom.go
  pkg/build/scanner.go
  pkg/manifest.go
  pkg/model/model.go
  pkg/publish/cmd.go
  pkg/publish/docker.go
  pkg/publish/gcs.go
  pkg/publish/github.go
  pkg/publish/grafana.go
  pkg/publish/helm.go
  pkg/source.go
  pkg/util/command.go
  pkg/util/files.go
  pkg/util/git.go
  pkg/validate/cmd.go
  pkg/validate/validate.go
  release/branch.sh
  release/build.sh
  test/publish.sh
Labels: size/XXL

#1492 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/report_build_info.sh
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1495 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1496 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1497 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1498 [1.18.rc.0] Step 2 - Build
  release/trigger-build
Labels: size/XS, release-notes-none

#1499 [1.18-rc.0] Step 3 - publish
  release/trigger-publish
Labels: size/XS, release-notes-none

#1500 Trigger release-1.17.3 build
  release/trigger-build
Labels: size/XS

#1502 [release-1.17] Retrigger a 1.17.3 build
  release/trigger-build
Labels: size/XS

#1503 [release-1.17] Retrigger 1.17.3 build - pick up new BASE_IMAGE
  release/trigger-build
Labels: size/XS
