Repository istio/release-builder, pull requests merged in 2023-01, with the labels that each got.

#1322 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1323 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1325 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1326 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
Labels: size/XS, auto-merge, release-notes-none

#1327 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1328 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1329 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1330 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1331 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1333 Fix branch commits not being created by user
  go.mod
  go.sum
  licenses/github.com/cloudflare/circl/LICENSE
  licenses/github.com/cloudflare/circl/ecc/p384/LICENSE
  licenses/github.com/pjbgf/sha1cd/LICENSE
  licenses/github.com/skeema/knownhosts/LICENSE
  pkg/util/git.go
Labels: size/XL

#1334 Also create a new branch in istio/repo (need in step 4)
  pkg/branch/createBranches.go
Labels: size/XS

#1335 [release-1.17] Automated branch step4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  go.mod
  go.sum
  licenses/github.com/cloudflare/circl/LICENSE
  licenses/github.com/cloudflare/circl/ecc/p384/LICENSE
  licenses/github.com/pjbgf/sha1cd/LICENSE
  licenses/github.com/skeema/knownhosts/LICENSE
  pkg/util/git.go
  release/build.sh
  test/publish.sh
Labels: size/XL

#1336 Move the CODEOWNERS change from step 4 to step 5 for common-files
  pkg/branch/updateCodeOwners.go
  pkg/branch/updateCommonFilesCommon.go
Labels: size/S

#1337 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1338 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1339 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1340 Remove the arm64 and amd64 images while searching for new image
  pkg/branch/updateCommonFilesCommon.go
Labels: size/XS

#1342 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1343 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1344 Fix for base image update missing Author in commit
  pkg/util/git.go
Labels: size/S

#1345 [release-1.17] Fix for base image update missing Author in commit
  pkg/util/git.go
Labels: size/S, release-notes-none

#1341 Trigger 1.17.0-beta.0 build
  release/trigger-build
Labels: size/XS

#1346 Trigger publish of release-1.17
  release/trigger-publish
Labels: size/XS

#1348 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1349 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1350 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1351 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#1352 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1353 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1354 architecture-var
  release/build.sh
  test/publish.sh
Labels: size/XS

#1355 Automator: update common-files@release-1.15 in istio/release-builder@release-1.15
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1356 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1357 Trigger release 1.15.5 build
  release/trigger-build
Labels: size/XS

#1358 trigger 1.16.2 build
  release/trigger-build
Labels: size/XS

#1360 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1361 Trigger 1.17.0-beta.1 build
  release/trigger-build
Labels: size/XS

#1362 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1359 trigger 1.16.2 publish
  release/trigger-publish
Labels: size/XS

#1363 trigger publish 1.15.5
  release/trigger-publish
Labels: size/XS

#1364 Trigger publish of release 1.17-beta.1
  release/trigger-publish
Labels: size/XS
