Repository istio/release-builder, pull requests merged in 2023-07, with the labels that each got.

#1561 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1562 Remove extraneous docker buildx create
  README.md
  pkg/build/scanner.go
Labels: size/XS

#1563 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1560 Create amd64 named artifacts for osx and win (for consistency)
  example/manifest.yaml
  pkg/build/archive.go
Labels: size/M

#1564 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1565 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1566 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1567 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1568 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1569 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1570 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1571 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1573 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1572 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1574 Automator: update common-files@release-1.16 in istio/release-builder@release-1.16
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1575 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1576 Automator: update common-files@release-1.17 in istio/release-builder@release-1.17
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1577 Automator: update common-files@release-1.18 in istio/release-builder@release-1.18
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1578 Trigger build of 1.17.4
  release/trigger-build
Labels: release-notes-none

#1580 Trigger build of 1.18.1
  release/trigger-build
Labels: size/XS, release-notes-none

#1579 Trigger build of 1.16.6
  release/trigger-build
Labels: size/XS, release-notes-none

#1581 Trigger publish of 1.17.4
  release/trigger-publish
Labels: size/XS, release-notes-none

#1582 Trigger publish of 1.18.1
  release/trigger-publish
Labels: size/XS, release-notes-none

#1583 Trigger publish of 1.16.6
  release/trigger-publish
Labels: size/XS, release-notes-none

#1584 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1585 base images: fix unsettting HUB
  pkg/util/command.go
Labels: size/XS, release-notes-none, cherrypick/release-1.17, cherrypick/release-1.18

#1586 [release-1.17] base images: fix unsettting HUB
  pkg/util/command.go
Labels: size/XS, release-notes-none

#1588 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1590 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1591 Trigger publish of 1.18.2
  release/trigger-publish
Labels: size/XS

#1592 Trigger publish of 1.17.5
  release/trigger-publish
Labels: size/XS

#1593 Trigger publish of 1.16.7
  release/trigger-publish
Labels: size/XS

#1594 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/tracing.sh
Labels: size/L, auto-merge, release-notes-none

#1596 Fix branch step 1.
  example/manifest_branch.yaml
  pkg/branch/updateDependencies.go
  release/trigger-branch
Labels: size/S

#1597 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
