Repository istio/release-builder, pull requests merged in 2024-07, with the labels that each got.

#1886 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1888 Automator: update common-files@release-1.21 in istio/release-builder@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1890 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1891 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1893 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1892 Publish istiod-remote Helm chart
  pkg/build/helm.go
Labels: size/XS

#1895 Trigger 1.21.5 build
  release/trigger-build
Labels: size/XS

#1894 Trigger 1.22.3 build
  release/trigger-build
Labels: size/XS

#1898 Trigger build for 1.23.0-alpha.0
  release/trigger-build
Labels: size/XS

#1899 Move wrapper to samples (part 1/2)
  pkg/build/helm.go
Labels: size/XS

#1900 Publish 1.23.0-alpha.0 build
  release/trigger-publish
Labels: size/XS

#1901 Move wrapper to samples (part 2/2)
  pkg/build/helm.go
  pkg/publish/cmd.go
  pkg/publish/helm.go
Labels: size/L

#1896 Trigger 1.21.5 publish
  release/trigger-publish
Labels: size/XS

#1897 Trigger 1.22.3 publish
  release/trigger-publish
Labels: size/XS

#1902 [release-1.23] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S

#1904 Automator: update common-files@release-1.23 in istio/release-builder@release-1.23
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1905 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1906 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1907 Remove operator from release
  pkg/build/archive.go
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: size/M, release-notes-none

#1908 Automator: update common-files@master in istio/release-builder@master
  Makefile
  common/.commonfiles.sha
  common/scripts/run.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1909 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1910 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
