Repository istio/release-builder, pull requests merged in 2024-04, with the labels that each got.

#1797 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1798 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/M, auto-merge, release-notes-none

#1799 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1800 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1802 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1803 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci-format.yml
Labels: size/M, auto-merge, release-notes-none

#1801 Automator: update common-files@release-1.21 in istio/release-builder@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1804 Trigger 1.21.1 build
  release/trigger-build
Labels: size/XS

#1807 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1806 Trigger 1.19.9 build
  release/trigger-build
Labels: size/XS

#1805 Trigger 1.20.5 build
  release/trigger-build
Labels: size/XS

#1808 Trigger 1.19.9 publish
  release/trigger-publish
Labels: size/XS

#1810 Trigger 1.21.1 publish
  release/trigger-publish
Labels: size/XS

#1811 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1812 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1813 Build initial 1.22.0-alpha.0
  release/trigger-build
Labels: size/XS

#1814 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1816 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1818 Trigger 1.20.6 build
  release/trigger-build
Labels: size/XS

#1815 Trigger 1.21.2 build
  release/trigger-build
Labels: size/XS

#1817 Trigger 1.19.10 build
  release/trigger-build
Labels: size/XS

#1822 Trigger a new build for 1.22.0-alpha.1
  release/trigger-build
Labels: size/XS

#1824 Trigger publish of 1.22.0-alpha.1
  release/trigger-publish
Labels: size/XS

#1825 [release-1.22] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S, release-notes-none

#1823 Trigger 1.19.10 publish
  release/trigger-publish
Labels: size/XS

#1819 Trigger 1.20.6 publish
  release/trigger-publish
Labels: size/XS

#1820 Trigger 1.21.2 publish
  release/trigger-publish
Labels: size/XS

#1826 Automator: update common-files@release-1.22 in istio/release-builder@release-1.22
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1827 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1828 Automator: update common-files@release-1.22 in istio/release-builder@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1831 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1830 [release-1.22] trigger 1.22.0 beta.0 build
  release/trigger-branch
  release/trigger-build
Labels: size/XS

#1832 [release-1.22] trigger 1.22.0 beta.0 publish
  release/trigger-publish
Labels: size/XS
