Repository istio/release-builder, pull requests merged in 2024-10, with the labels that each got.

#1946 Remove `istiod-remote` chart (https://github.com/istio/istio/pull/53294)
  pkg/build/helm.go
  pkg/validate/validate.go
Labels: size/XS

#1947 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1948 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1949 Automator: update common-files@release-1.23 in istio/release-builder@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1950 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1951 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1952 Publish ztunnel grafana dashboard
  release/build.sh
Labels: size/XS, release-notes-none, cherrypick/release-1.23

#1953 [release-1.23] Publish ztunnel grafana dashboard
  release/build.sh
Labels: size/XS, release-notes-none

#1954 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1955 trigger 1.24.0-alpha.0 build
  release/trigger-build
Labels: size/XS

#1956 trigger 1.24.0-alpha.0 publish
  release/trigger-publish
Labels: size/XS

#1957 [release-1.22] build 1.22.6
  release/trigger-build
Labels: size/XS

#1959 Build Istio 1.23.3 artifacts
  release/trigger-build
Labels: size/XS

#1958 [release-1.22] publish 1.22.6
  release/trigger-publish
Labels: size/XS

#1960 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/XS, auto-merge, release-notes-none

#1961 Publish 1.23.3
  release/trigger-publish
Labels: size/XS

#1962 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1963 Trigger automation step 4 for 1.24
  release/trigger-branch
Labels: size/XS

#1964 [release-1.24] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S, release-notes-none

#1966 Automator: update common-files@release-1.24 in istio/release-builder@release-1.24
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1967 Trigger build of 1.24.0-rc.0
  release/trigger-build
Labels: size/XS

#1968 Publish 1.24 rc0
  release/trigger-publish
Labels: size/XS, release-notes-none
