Repository istio/release-builder, pull requests merged in 2024-02, with the labels that each got.

#1745 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1746 [release-1.21] Trigger a build of 1.21.0-beta.1
  release/trigger-build
Labels: size/XS

#1747 [release-1.21] Trigger a publish of 1.21.0-beta.1
  release/trigger-publish
Labels: size/XS

#1748 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1749 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1750 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1752 Trigger publish for 1.19.7
  release/trigger-publish
Labels: size/XS

#1753 Trigger publish for 1.20.3
  release/trigger-publish
Labels: size/XS

#1754 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1755 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1756 Automator: update common-files@master in istio/release-builder@master
  SUPPORT.md
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none

#1757 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/M, auto-merge, release-notes-none

#1758 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1759 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1762 rc-0 build for 1.21
  release/trigger-build
Labels: size/XS

#1763 publish rc.0 for 1.21
  release/trigger-publish
Labels: size/XS

#1751 Specify go 1.22
  go.mod
  go.sum
Labels: size/M

#1765 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1766 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
  common/scripts/metallb-native.yaml
Labels: size/L, auto-merge, release-notes-none

#1767 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1768 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1769 Remove manifest samples check
  pkg/build/archive.go
Labels: size/XS
