Repository istio/release-builder, pull requests merged in 2024-08, with the labels that each got.

#1912 Trigger build for 1.23.0-rc.0
  release/trigger-build
Labels: size/XS

#1913 Trigger publish for 1.23.0-rc.0
  release/trigger-publish
Labels: size/XS

#1914 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1915 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1916 Automator: update common-files@release-1.22 in istio/release-builder@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1917 Automator: update common-files@release-1.23 in istio/release-builder@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1918 Trigger build for 1.23.0-rc.1
  release/trigger-build
Labels: size/XS

#1919 Publish build for 1.23.0-rc.1
  release/trigger-publish
Labels: size/XS

#1922 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1921 Trigger publish for 1.23.0
  release/trigger-publish
Labels: size/XS

#1924 [Release-1.22] publish 1.22.4
  release/trigger-publish
Labels: size/XS

#1925 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1927 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1928 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none
