Repository istio/release-builder, pull requests merged in 2024-09, with the labels that each got.

#1930 Build Istio 1.23.1 artifacts
  release/trigger-build
Labels: size/XS

#1932 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1931 Re-trigger 1.23.1 build again
  release/trigger-build
Labels: size/XS

#1936 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1937 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#1934 Adopt release builder to #53067
  pkg/validate/validate.go
Labels: size/S, release-notes-none

#1939 Trigger publish for 1.23.2
  release/trigger-publish
Labels: size/XS

#1938 Trigger publish for 1.22.5
  release/trigger-publish
Labels: size/XS

#1941 [release-1.21] build 1.21.6
  release/trigger-build
Labels: size/XS

#1944 [release-1.21] build 1.21.6 (attempt 2)
  release/trigger-build
Labels: size/XS

#1942 [release-1.21] publish 1.21.6
  release/trigger-publish
Labels: size/XS

#1943 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1945 Automator: update common-files@release-1.21 in istio/release-builder@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
