Repository istio/release-builder, pull requests merged in 2024-01, with the labels that each got.

#1719 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1720 Trigger build for 1.19.6
  release/trigger-build
Labels: size/XS

#1721 Trigger build for 1.20.2
  release/trigger-build
Labels: size/XS

#1722 Trigger 1.18.7 publish
  release/trigger-publish
Labels: size/XS

#1724 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1723 Trigger publish for 1.19.6
  release/trigger-publish
Labels: size/XS

#1717 Support new helm chart structure in validation
  pkg/validate/validate.go
Labels: size/S, release-notes-none

#1725 Trigger 1.20.2 publish
  release/trigger-publish
Labels: size/XS

#1727 Fix path traversal for new defaults values
  pkg/validate/validate.go
Labels: size/XS, release-notes-none

#1729 Automator: update common-files@release-1.19 in istio/release-builder@release-1.19
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1730 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1731 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1732 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1733 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1734 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1735 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1736 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1737 [release-1.21] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S, release-notes-none

#1740 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1739 Trigger 1.21.0-beta.0 build
  release/trigger-build
Labels: size/XS

#1742 Update deps
  go.mod
  go.sum
Labels: size/L

#1743 [release-1.21] Update build-base-images to use 1.21 branch
  release/build-base-images.sh
Labels: size/XS

#1744 Automator: update common-files@master in istio/release-builder@master
  .gitattributes
  common/.commonfiles.sha
Labels: size/XS, auto-merge, release-notes-none
