Repository istio/release-builder, pull requests merged in 2024-06, with the labels that each got.

#1857 Filter non-dashboard files in grafana
  pkg/build/grafana.go
Labels: size/XS, release-notes-none

#1858 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.golangci.yml
Labels: size/S, auto-merge, release-notes-none

#1859 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1860 Only copy actual dashboards for grafana
  pkg/build/grafana.go
Labels: size/S, release-notes-none

#1862 Trigger 1.20.7 publish
  release/trigger-publish
Labels: size/XS

#1863 Trigger 1.21.3 publish
  release/trigger-publish
Labels: size/XS

#1864 Trigger 1.22.1 publish
  release/trigger-publish
Labels: size/XS

#1866 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1867 Fix versioning issues
  example/manifest.yaml
  release/build-base-images.sh
  release/build.sh
  test/publish.sh
Labels: size/S, release-notes-none

#1861 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#1868 Automator: update common-files@release-1.21 in istio/release-builder@release-1.21
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1869 Automator: update common-files@release-1.22 in istio/release-builder@release-1.22
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1870 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/Makefile.common.mk
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1855 Update dependencies
  go.mod
  go.sum
  licenses/go.uber.org/zap/LICENSE
Labels: size/L

#1872 version validate by json marshal
  pkg/validate/validate.go
Labels: size/M

#1873 [release-1.20] trigger 1.20.8 build
  release/trigger-build
Labels: size/XS

#1877 Fix branch for 1.22 base images
  release/build-base-images.sh
Labels: size/XS, release-notes-none

#1874 brancher: fix base image update
  pkg/branch/istioReleaseBuilderUpdates.go
Labels: size/XS, release-notes-none

#1878 [release-1.22] trigger 1.22.2 build
  release/trigger-build
Labels: size/XS

#1879 Trigger 1.21.4 build
  release/trigger-build
Labels: size/XS

#1880 [release-1.22] publish 1.22.2 build
  release/trigger-publish
Labels: size/XS

#1881 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/check_clean_repo.sh
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1884 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#1883 Trigger 1.22.2 publish, attempt 2
  release/trigger-publish
Labels: size/XS

#1882 Trigger 1.21.4 publish
  release/trigger-publish
Labels: size/XS
