Repository istio/release-builder, pull requests merged in 2024-05, with the labels that each got.

#1835 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1836 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1833 [release-1.22] trigger 1.22.0 beta.1 build
  release/trigger-build
Labels: size/XS

#1834 [release-1.22] trigger 1.22.0 beta.1 publish
  release/trigger-publish
Labels: size/XS

#1838 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/.hadolint.yml
Labels: size/XS, auto-merge, release-notes-none

#1841 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1839 [Release-1.22] trigger build 1.22.0-rc.0
  release/trigger-build
Labels: size/XS

#1840 [Release-1.22] trigger push 1.22.0-rc.0
  release/trigger-publish
Labels: size/XS

#1842 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1845 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1843 [release-1.22] trigger 1.22.0 build
  release/trigger-build
Labels: size/XS

#1844 [release-1.22] trigger 1.22.0 publish
  release/trigger-publish
Labels: size/XS

#1846 Automator: update common-files@release-1.20 in istio/release-builder@release-1.20
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1847 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1848 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1850 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1849 Improve helm chart.yaml parsing a bit, handle dep updates
  go.mod
  go.sum
  licenses/helm.sh/helm/v3/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/frobnitz.v1/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/frobnitz.v2.reqs/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/frobnitz/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/frobnitz_backslash/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/frobnitz_with_bom/LICENSE
  licenses/helm.sh/helm/v3/pkg/chart/loader/testdata/frobnitz_with_dev_null/LICENSE
  licenses/helm.sh/helm/v3/pkg/chartutil/testdata/dependent-chart-alias/LICENSE
  licenses/helm.sh/helm/v3/pkg/chartutil/testdata/dependent-chart-no-requirements-yaml/LICENSE
  licenses/helm.sh/helm/v3/pkg/chartutil/testdata/dependent-chart-with-all-in-requirements-yaml/LICENSE
  licenses/helm.sh/helm/v3/pkg/chartutil/testdata/dependent-chart-with-mixed-requirements-yaml/LICENSE
  licenses/helm.sh/helm/v3/pkg/chartutil/testdata/frobnitz/LICENSE
  pkg/build/archive.go
  pkg/build/helm.go
  pkg/build/helm_test.go
  pkg/build/testdata/chart-deps-in.yaml
  pkg/build/testdata/chart-values-in.yaml
Labels: size/L

#1853 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1854 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1856 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none
