Repository istio/release-builder, pull requests merged in 2025-02, with the labels that each got.

#2027 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2028 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2031 trigger rebuild for 1.24.3
  release/trigger-build
Labels: size/XS

#2034 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2030 [release-1.24] publish 1.24.3
  release/trigger-publish
Labels: size/XS

#2033 [release-1.25] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S, release-notes-none

#2032 run prowtrans after generating config
  pkg/branch/setupProw.go
Labels: size/XS

#2035 Automator: update common-files@release-1.25 in istio/release-builder@release-1.25
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2036 Publish 1.23.5
  release/trigger-publish
Labels: size/XS

#2037 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2038 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2039 trigger build of 1.25.0-rc.0
  release/trigger-build
Labels: size/XS

#2040 Trigger publish for 1.25.0-rc.0
  release/trigger-publish
Labels: size/XS

#2041 Trigger build for 1.25.0-rc.1
  release/trigger-build
Labels: size/XS

#2042 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2043 Publish 1.25.0-rc.1
  release/trigger-publish
Labels: size/XS

#2044 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/run.sh
Labels: size/XS, auto-merge, release-notes-none

#2046 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2047 trigger 1.25.0 build
  release/trigger-build
Labels: size/XS
