Repository istio/release-builder, pull requests merged in 2025-07, with the labels that each got.

#2132 publish 1.27.0-alpha.0
  release/trigger-publish
Labels: size/XS

#2133 [release-1.27] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S

#2134 allow create PR from a fork repo target istio org
  pkg/branch/branch.go
  pkg/branch/cmd.go
  pkg/build/scanner.go
  pkg/util/git.go
  release/branch.sh
Labels: size/M

#2136 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2137 Automator: update common-files@release-1.26 in istio/release-builder@release-1.26
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2140 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci.yml
  common/scripts/setup_env.sh
Labels: size/S, auto-merge, release-notes-none

#2142 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2145 trigger 1.25.4 build
  release/trigger-build
Labels: size/XS

#2146 [release-1.27] trigger build beta.0
  release/trigger-build
Labels: size/XS

#2147 [release-1.27] trigger publish beta.0
  release/trigger-publish
Labels: size/XS

#2144 trigger publish 1.26.3
  release/trigger-publish
Labels: size/XS
