Repository istio/release-builder, pull requests merged in 2025-04, with the labels that each got.

#2068 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2066 Automator: update common-files@release-1.23 in istio/release-builder@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2070 trigger 1.23.6 publish
  release/trigger-publish
Labels: size/XS

#2071 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2072 Automator: update common-files@release-1.23 in istio/release-builder@release-1.23
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2073 Automator: update common-files@release-1.24 in istio/release-builder@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2074 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/config/.golangci-format.yml
  common/config/.golangci.yml
  common/config/license-lint.yml
  common/scripts/format_go.sh
  common/scripts/lint_go.sh
  common/scripts/setup_env.sh
Labels: size/XL, auto-merge, release-notes-none

#2080 Automator: update common-files@release-1.25 in istio/release-builder@release-1.25
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2076 [release-1.24] trigger 1.24.5 build
  release/trigger-build
Labels: size/XS

#2077 [release-1.25] trigger 1.25.2 build
  release/trigger-build
Labels: size/XS

#2078 [release-1.25] trigger 1.25.2 publish
  release/trigger-publish
Labels: size/XS

#2079 [release-1.24] trigger 1.24.5 publish
  release/trigger-publish
Labels: size/XS

#2082 build 1.26.0-alpha.0
  release/trigger-build
Labels: size/XS

#2083 publish 1.26.0-alpha.0
  release/trigger-publish
Labels: size/XS

#2087 [release-1.26] Automated branching step 4
  CODEOWNERS
  common/Makefile.common.mk
  example/manifest.yaml
  release/build.sh
  test/publish.sh
Labels: size/S, release-notes-none

#2088 Automator: update common-files@release-1.26 in istio/release-builder@release-1.26
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2089 [release-1.26] build 1.26.0-beta.0
  release/trigger-build
Labels: size/XS

#2085 bump golang.org/x/net
  go.mod
  go.sum
Labels: size/M

#2092 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2093 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2094 [release-1.26] trigger build 1.26.0-rc.0
  release/trigger-build
Labels: size/XS

#2095 [release-1.26] trigger publish 1.26.0-rc.0
  release/trigger-publish
Labels: size/XS
