Repository istio/release-builder, pull requests merged in 2025-01, with the labels that each got.

#1997 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#1999 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2000 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2002 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/config/license-lint.yml
Labels: size/XS, auto-merge, release-notes-none

#2003 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2004 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2005 Automator: update common-files@release-1.24 in istio/release-builder@release-1.24
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2008 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2009 skip tagging images by default
  pkg/branch/setupProw.go
Labels: size/XS

#2012 trigger 1.25.0-alpha.0 build
  release/trigger-build
Labels: size/XS

#2013 trigger 1.25.0-alpha.0 publish
  release/trigger-publish
Labels: size/XS

#2014 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2016 [release-1.24] build 1.24.3
  release/trigger-build
Labels: size/XS

#2018 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/S, auto-merge, release-notes-none

#2019 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2010 [release-1.22] publish 1.22.8
  release/trigger-publish
Labels: size/XS

#2020 modify update-go-control-plane steps
  pkg/branch/updateDependencies.go
Labels: size/S

#2021 fall back to bind mount gitconfig user email
  pkg/util/git.go
Labels: size/S

#2023 Automator: update common-files@master in istio/release-builder@master
  common/.commonfiles.sha
  common/scripts/kind_provisioner.sh
Labels: size/XS, auto-merge, release-notes-none

#2022 [release-1.24] retrigger build 1.24.3
  release/trigger-build
Labels: size/XS

#2024 Specify skip-gar-tagging in the right format
  pkg/branch/setupProw.go
Labels: size/XS

#2025 specify input dirs for prowgen commands
  pkg/branch/setupProw.go
Labels: size/S

#2026 run prowgen write after generating new config
  pkg/branch/setupProw.go
Labels: size/S
