Repository istio/release-builder, pull requests merged in 2025-05, with the labels that each got.

#2099 [release-1.26] trigger 1.26.0 build
  release/trigger-build
Labels: size/XS

#2101 [release-1.26] trigger rebuild of 1.26.0
  release/trigger-build
Labels: size/XS

#2102 [release-1.26] rebuild 1.26
  release/trigger-build
Labels: size/XS

#2100 [release-1.26] trigger 1.26.0 publish
  release/trigger-publish
Labels: size/XS

#2106 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2107 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2104 trigger 1.25.3 build
  release/trigger-build
Labels: size/XS

#2105 trigger 1.24.6 build
  release/trigger-build
Labels: size/XS

#2110 [release-1.25] trigger 1.25.3 publish
  release/trigger-publish
Labels: size/XS

#2108 Dependabot/go modules/helm.sh/helm/v3 3.17.3
  go.mod
  go.sum
Labels: size/S

#2109 [release-1.24] publish 1.24.6
  release/trigger-publish
Labels: size/XS

#2111 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2112 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2114 Automator: update common-files@master in istio/release-builder@master
  .devcontainer/devcontainer.json
  common/.commonfiles.sha
  common/scripts/setup_env.sh
Labels: size/XS, auto-merge, release-notes-none

#2115 Trigger 1.26.1 build
  release/trigger-build
Labels: size/XS

#2116 Trigger 1.26.1 publish
  release/trigger-publish
Labels: size/XS
